### ISSUE TITLE
HTTP DB backend

### ISSUE THREAD

**Issue by tebeka** [mlrun/mlrun#1]
@yaronha said:

> add an HTTP DB backend, see https://github.com/v3io/mlrun/tree/master/mlrun/db
> 
> need to implement a client based on the base class which proxy (map the api to HTTP requests) to a remote server (which can run the FileDB class behind a restful API)

**Comment by tebeka** [comment]
How about [MLflow](https://mlflow.org)?

**Comment by yaronha** [comment]
@tebeka that one too, BTW have a panel on that (KubeFlow, MLFlow, MLrun) on Monday

**Comment by tebeka** [comment]
Fixed in #5
