### ISSUE TITLE
MLRun components installing but not opening

### ISSUE THREAD

**Issue by felipemmelo** [mlrun/mlrun#1037]
Hi,

I've installed Mlrun like this:

```
export ip=$(minikube ip)

helm --namespace mlrun \                   
    install mlrun-kit \
    --wait \
    --set global.registry.url=https://index.docker.io/v2/ \
    --set global.registry.secretName=registry-credentials \
   --set global.externalHostAddress=$ip \
    v3io-stable/mlrun-kit
```

and it seems to succeed by giving the output:

```
NAME: mlrun-kit
LAST DEPLOYED: Mon Jun 21 13:27:13 2021
NAMESPACE: mlrun
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You're up and running !

1. Jupyter UI is available at:
  http://IP:30040

2. Nuclio UI is available at:
  http://IP:30050

3. MLRun UI is available at:
  http://IP:30060

4. MLRun API is exposed externally at:
  http://IP:30070

Happy MLOPSing !!! :]

```

But when I try to access Jupyter, for example, it hangs for a long time until failing.

**Comment by Hedingber** [comment]
Hi @felipemmelo 
Thanks for reaching out!
Can you give some more details on your env? (OS, version, minikube version, k8s version, etc...)
Also what's the status of the pods ? (`kubectl --namespace mlrun get pods`)
Unrelated - note that the value you give to `global.registry.url` seems invalid, it should be something like `index.docker.io/hedingber` i.e. a link to **your** docker registry.

**Comment by Hedingber** [comment]
No response, closing
