### ISSUE TITLE
Loading mlrun DataItems into Dask DataFrames Failing

### ISSUE THREAD

**Issue by hayesgb** [mlrun/mlrun#1142]
Executing `mlrun.get_dataitem("az://{container}/<path_to_blob>.parquet").as_df(df_module=dd)` fails when the `"az://{container}/<path_to_blob>.parquet"` is a file, rather than a directory.

This is because Dask expects to receive storage_options, but it is skipped to support Pandas regression.

Additionally, Dask does not support dropping data inplace.

**Comment by Hedingber** [comment]
@hayesgb this can be closed now that https://github.com/mlrun/mlrun/pull/1143 is merged right ?

**Comment by hayesgb** [comment]
Yes
