### ISSUE TITLE
Option to run tests against k8s cluster

### ISSUE THREAD

**Issue by tebeka** [mlrun/mlrun#122]

**Comment by tebeka** [comment]
We'll need to set a secret in circleci for that. See #74

**Comment by tebeka** [comment]
@yaronha said:
>  i was thinking that we need that we need access to k8s API not just the end-point since build will need to load a new api service container version on the cluster
> before running teest w the client of that ver

**Comment by tebeka** [comment]
@yaronha The test should be then:
- Build image from current code
- Deploy image to k8s cluster
- Wait for pod to be ready
- Run tests against pod

**Comment by Hedingber** [comment]
We implemented a system test (the system includes a k8s cluster) mechanism some time ago, closing
