### ISSUE TITLE
Move httpd out of "db" directory

### ISSUE THREAD

**Issue by tebeka** [mlrun/mlrun#123]
It does more than just a backend to db

**Comment by tebeka** [comment]
I suggest the following split (from current routing).

### submit
/api/submit
/api/submit/
/api/submit_job
/api/submit_job/
/api/submit_pipeline
/api/submit_pipeline/

### functions
/api/build/function
/api/build/function/
/api/start/function
/api/start/function/
/api/status/function
/api/status/function/

### status
/api/build/status
/api/build/status/

### files
/api/files
/api/filestat

### logs
/api/log/<project>/<uid>
/api/log/<project>/<uid>

### runs
/api/run/<project>/<uid>
/api/run/<project>/<uid>
/api/run/<project>/<uid>
/api/run/<project>/<uid>
/api/runs
/api/runs

### artifacts
/api/artifact/<project>/<uid>/<path:key>
/api/projects/<project>/artifact-tags
/api/artifact/<project>/<tag>/<path:key>
/api/artifact/<project>/<uid>
/api/artifacts
/api/artifacts

### functions
/api/func/<project>/<name>
/api/func/<project>/<name>
/api/funcs

### projects
/api/project
/api/project/<name>
/api/project/<name>
/api/projects

### schedule
/api/schedules

### tags
/api/<project>/tag/<name>
/api/<project>/tag/<name>
/api/<project>/tags
/api/<project>/tag/<name>

### admin
/api/healthz


@yaronha What do you think?

**Comment by Hedingber** [comment]
Already done long time ago, closing
