### ISSUE TITLE
Azure Container Registry Unauthorized

### ISSUE THREAD

**Issue by linhy1993** [mlrun/mlrun#1514]
Hello,
I am trying to push the model image to my Azure Container Registry, but I meet the error:

`stderr: unauthorized: authentication required `

I install mlrun by using Helm:

```
helm --namespace mlrun install mlrun-kit 
--wait \
--set global.registry.url=myregistry.azurecr.io \
--set global.registry.secretName=registry-credentials \
v3io-stable/mlrun-ki
```

and also secrets

```
kubectl create secret docker-registry registry-credentials --namespace mlrun \
    --docker-username myusername \
    --docker-password mypassword \
    --docker-server myregistry.azurecr.io 
```

I can log in on local to push images by using 
`docker push myregistry.azurecr.io/processor-quick-start-jovyan-v2-model-server`

I am wondering does it support Azure Container Registry or just docker hub?

Thanks in advance!

**Comment by Hedingber** [comment]
Hi @linhy1993,
Thanks for reaching out!
Note the examples we have in the [installation instructions](https://docs.mlrun.org/en/latest/install.html) for docker hub:
* For the secret the docker server would be something like - `https://index.docker.io/v1/`
* For the url (in the helm command) it would be something like - `index.docker.io/hedingber`

So for your case:
* For the secret, by looking [here](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes#create-an-image-pull-secret) it looks like it should be `myregistry.azurecr.io` which is what you did, though I would also give a try to `https://myregistry.azurecr.io`
* For the url I think the `myregistry.azurecr.io` is ok

We did tried with other registries than docker hub, quay.io for example, but I'm suspecting that maybe somewhere in our code we're expecting a <registry>/<repo/username> structure and not like it is for azure (<repo/username>.<registry>)

Can you please give some more details:
* What code did you run
* What was the full output
* Assuming you trigger an image building with mlrun, a kaniko pod should have been created, can you send logs for that pod and it's full spec (`kubectl get po <pod-name> -o yaml`)
* What was in the mlrun-api logs

**Comment by Hedingber** [comment]
No response, closing
Feel free to reopen
