### ISSUE TITLE
Nuclio api gateway

### ISSUE THREAD

**Issue by ran-haim** [mlrun/mlrun#1531]
Hi,
I can't get api gateway to work.
I see in the UI, that it is ready but I can't get response from it.

I can't see any document on how to use it, I am not sure I am using it correctly (what endpoint should I enter?)

thanks.

**Comment by Hedingber** [comment]
Hi @ran-haim 
The API Gateways mechanism is based on Kubernetes ingresses - in order for that to work an ingress controller is needed - this is not included as part of the mlrun-kit

**Comment by ran-haim** [comment]
Hi,
I've got istio installed.
Is there a document for setting API Gateways with istio?

**Comment by Hedingber** [comment]
@ran-haim 
First of all to get the best support for Nuclio itself I suggest opening the issue there
I'm also a contributor to Nuclio myself, so will try to help
I never used Istio myself, but from what I understand it's a service mesh, meaning, like Nuclio's API Gateways, it gives some abstraction layer on top of the kubernetes "basic networking features".
Nuclio doesn't support using Istio as the infrastructure for the API Gateways, but it doesn't mean they can't work together.
All you need for Nuclio API Gateways to work is the nginx ingress controller. From reading [this one](https://www.giffgaff.io/tech/using-istio-with-nginx-ingress) it seems like it is possible to combine the two.

**Comment by Hedingber** [comment]
@liranbg Feel free to jump in and add your insights/opinions

**Comment by alonmr** [comment]
There has been a lot of work on api gateway for 1.7 (started in https://github.com/mlrun/mlrun/pull/4742)
Since this issue is stale I'm closing. If still an issue with 1.7 please add reproduction steps.
