### ISSUE TITLE
Missing information about period

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#1583]
Documentation issue:

- please, add information about supported values (day, minute, second, etc. probably not year) for parametr **period** in function **add_aggregation** (see link https://docs.mlrun.org/en/latest/api/mlrun.feature_store.html#mlrun.feature_store.FeatureSet.add_aggregation)

**Comment by jillnogold** [comment]
Already updated: https://github.com/mlrun/mlrun/pull/1580
Do you want anything else there?

**Comment by george0st** [comment]
No, thanks

**Comment by Hedingber** [comment]
Merged, closing
