### ISSUE TITLE
Missing information about restrictions for definition of feature name

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#1584]
Documentation issues:
 - please add information about restrictions for definition of feature name such as 'avoid the prefixes **t_** and **aggr_**' also avoid special chars such as '**-**', '**#**', '**@**', etc.

**Comment by jillnogold** [comment]
already updated:https://github.com/mlrun/mlrun/pull/1581
Any further requests?

**Comment by george0st** [comment]
No, thanks

**Comment by Hedingber** [comment]
Merged, closing
