### ISSUE TITLE
FeatureStore, Ingestion - add support for Spark dataframe

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#1595]
It will be very useful to add support for Spart dataframe to the **mlrun.feature_store.ingest** (not only support pandas dataframe).

BTW: 
- It can improve work with historical data in phase of experiments, model discovery and model building (it is about focus on off-line feature store)
- It will help with better utilization of Spark engine

**Comment by adiso75** [comment]
@george0st we've added it to our plan
