### ISSUE TITLE
class MapValues - support mapping for non-string values also

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#1598]
Add support for mapping non-string values in **class MapValues** (it is part of mlrun/feature_store/steps.py).

E.g. this code does not work, because you are supporting only map string to string values

`feature_set.graph.add_step(MapValues(mapping={'fn3': {2: 22}}, with_original_features=True))`

**Comment by adiso75** [comment]
@george0st we've added it to the plan

**Comment by george0st** [comment]
Implemented
