### ISSUE TITLE
Documentation - add Glossary

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#1616]
LOW PRIORITY

It will be useful for newcomers and faster on-boarding to provide Glossary as part of section https://docs.mlrun.org/ -> References (where are API Index, API By Module, ...). I can imagine the content (expected structure - abbreviation, area, description):

- hub - link to market place (alias to git...)
- v3io - internal specification of file format (v3io://) and streaming ...
- s3 - location to Amazon object storage
- DAG - directed acyclic graph (usage in FeatureSet.graph, ...)
- EDA - ???
- storey - ??? relation to v3io ???
- HTTPRunDB - API for wrapper to the internal DB in MLRun
- ctx - common abbreviation for context
- Project - ...
- Feature - raw data or a calculation derived from one or more other features
- FeatureSet - group of features, ...
- FeatureVector - query to feature sets with ability to join, filer, etc. more see ...
- Event - part of streaming ... relation of event to row in FeatureSet
- v3io shard - partition of items ...
- ...

**Comment by adiso75** [comment]
@george0st good idea. we'll do it
