### ISSUE TITLE
Invalid link(s) - Identity\User\Policies\Read more

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#1705]
I saw invalid link in Iguazio version 3.0.3 in part **Identity\User\Policies\Read more** see print screen. 

**Invalid link in Iguazio**
![image](https://user-images.githubusercontent.com/95856749/152184575-b1186e77-6e05-486c-9fa2-a38745a9f4a5.png)

**Output**
![image](https://user-images.githubusercontent.com/95856749/152184870-dcb2f032-b18e-445d-8072-0541b02315c3.png)

**Invalid links in 'https://www.iguazio.com/docs/latest-release/'**
I saw a few invalid links in URL 'https://www.iguazio.com/docs/' also (it is possible easy find out invalid links see https://www.deadlinkchecker.com/ ,but it can generate DoS also)

- https://www.iguazio.com/latest-release/	Documentation
- https://www.iguazio.com/solutions/real-time-feature-engineering/	Real Time Feature Engineering
- https://www.iguazio.com/introduction-to-tf-serving/	Introduction to TF Serving
- https://www.iguazio.com/odscwest2021/	ODSC West Conference- Top 6 Sessions You Must Attend
- https://www.iguazio.com/it-worked-fine-in-jupyter-now-what/	It Worked Fine in Jupyter. Now What?

![image](https://user-images.githubusercontent.com/95856749/152223812-0e892a17-59ab-45c1-bb3c-72b91b3cfdf9.png)

**Comment by EdmondIguazio** [comment]
Opened a JIRA ticket:
https://jira.iguazeng.com/browse/IG-20140
