### ISSUE TITLE
Extend Policies - Add role "On-line FS Read only access"

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#1706]
**Priority:** 

- Medium

**Motivation:** 

- We see possible risk in case, that we will have one environment with on/off-line feature store and a developer can make mistake and will write data to on-line feature store also

**Requirement:**

- it will be fine to have Policies/Roles "On-line FS Read only access" with ability to manage, who can write data to on-line feature store
- it means extend list of Policies/Roles see print screen

![image](https://user-images.githubusercontent.com/95856749/152188652-3ff1d348-1afe-4446-a271-c96a2f47ef84.png)

**Comment by EdmondIguazio** [comment]
Opened a JIRA ticket:
https://jira.iguazeng.com/browse/IG-20141
