### ISSUE TITLE
Create "tags" table

### ISSUE THREAD

**Issue by tebeka** [mlrun/mlrun#171]
We'd like to have a `tags` table that maps `tag -> uid` (like how `git tag` works)
Then we can remove the `tag` field from artifacts and others.

`tag *` is like tag all latest

**Comment by tebeka** [comment]
@yaronha Please review [the RFC](https://docs.google.com/document/d/1rmlylHiw2pY8dmT23FA7fkZ2razHIo104smxpJGEDWQ/edit#heading=h.vmxl9b7n036s). I'm begging to implement

**Comment by tebeka** [comment]
Fix: in artifact `tag -> (project, key, uid)`

**Comment by tebeka** [comment]
For function key is `(project, name, uid)`

**Comment by tebeka** [comment]
@yaronha If you look at the [suggested new data schema](https://docs.google.com/document/d/1Ef6_AAINl6D09jcQgYjNxSSLTpoNfH1xSkqMf9fR8KA/edit). Artifact should connect to the run it came from so tags should be on the run,  not the artifact.

**Comment by yaronha** [comment]
> @yaronha Please review [the RFC](https://docs.google.com/document/d/1rmlylHiw2pY8dmT23FA7fkZ2razHIo104smxpJGEDWQ/edit#heading=h.vmxl9b7n036s). I'm beggining to implement

@tebeka the urls are all gradually changing to `project` first, i.e. `/project/<project-name>/tags`
in post/put  use data from json struct vs URL  i.e. `{'type': 'xx, ..}`
in get we should focus on list tags first (not much vale in get_tag)
