### ISSUE TITLE
Installing mlrun on k8s cluster error

### ISSUE THREAD

**Issue by mrxuehb** [mlrun/mlrun#1750]
Hello,
When I following the instructions and installing mlrun on k8s cluster, it fails at:
helm --namespace mlrun \
    install mlrun-kit \
    --wait \
    --set global.registry.url=<registry-url> \
    --set global.registry.secretName=registry-credentials \
    v3io-stable/mlrun-kit
The error shows 'Error: timed out waiting for the condition'.

'kubectl get pod -n mlrun' shows:
![image](https://user-images.githubusercontent.com/5998563/153833193-287a92ca-89ae-4e2d-8f1d-0848772ee823.png)

'kubectl describe pod mlrun-kit-mpi-operator-786b5b489c-7s4mg -n mlrun' show:
Name:         mlrun-kit-mpi-operator-786b5b489c-7s4mg
Namespace:    mlrun
Priority:     0
Node:         k8s-test-worker-2/192.168.31.188
Start Time:   Mon, 14 Feb 2022 16:56:38 +0800
Labels:       app=mpi-operator
              chart=mpi-operator-0.4.5
              component=mpi-operator
              crd-version=v1
              heritage=Helm
              pod-template-hash=786b5b489c
              release=mlrun-kit
Annotations:  <none>
Status:       Pending
IP:           10.0.2.146
IPs:
  IP:           10.0.2.146
Controlled By:  ReplicaSet/mlrun-kit-mpi-operator-786b5b489c
Containers:
  mlrun-kit-mpi-operator:
    Container ID:
    Image:         gcr.io/iguazio/mpi-operator:v0.2.3-igz
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/mpi-operator.v1
    Args:
      -alsologtostderr
      --kubectl-delivery-image
      mpioperator/kubectl-delivery:v0.2.3
      --namespace
      mlrun
      --lock-namespace
      mlrun
    State:          Waiting
      Reason:       ErrImagePull
    Ready:          False
    Restart Count:  0
    Environment:
      KUBEFLOW_NAMESPACE:  mlrun
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from mpi-operator-token-bxj9j (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  mpi-operator-token-bxj9j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mpi-operator-token-bxj9j
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  10m                    default-scheduler  Successfully assigned mlrun/mlrun-kit-mpi-operator-786b5b489c-7s4mg to k8s-test-worker-2
  Normal   Pulling    7m29s (x2 over 9m58s)  kubelet            Pulling image "gcr.io/iguazio/mpi-operator:v0.2.3-igz"
  Warning  Failed     7m14s (x2 over 9m43s)  kubelet            Failed to pull image "gcr.io/iguazio/mpi-operator:v0.2.3-igz": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     7m14s (x2 over 9m43s)  kubelet            Error: ErrImagePull

It seems that docker image "gcr.io/iguazio/mpi-operator:v0.2.3-igz" is missing. Is this the problem?

Thanks.

**Comment by mrxuehb** [comment]
@Tankilevitch Thanks for your reply. I have tried 'docker pull gcr.io/iguazio/mpi-operator:v0.2.3-igz', it failed with message:
Error response from daemon: Get "https://gcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Seems a network connection problem? But my connection is ok with gcs and so on.

Is this stored in your private hub?

Thanks.

**Comment by mrxuehb** [comment]
It may be due to  that I cannot access all  'gcr.io'  resources.   Can I use other mpi-operator image instead?

**Comment by Tankilevitch** [comment]
Hi, @mrxuehb. Because it appears that you are having an issue with gcr.io, I have pushed our mpi-operator to dockerhub for the time being.
I would recommend following this guide https://docs.mlrun.org/en/latest/install.html#uninstalling-the-chart to ensure you clean your environment before proceeding with the installation guide.
Run the following in your helm installation step:
helm --namespace mlrun \\
   install mlrun-kit \\
   --wait \\
   **--set mpi-operator.image.deployment.repository=mlrun/mpi-operator** \ \
   --set global.registry.url=index.docker.io/\<your user> \ \
   --set global.registry.secretName=registry-credentials \ \
   v3io-stable/mlrun-kit

**Comment by mrxuehb** [comment]
Thank you for your time. It helps.
