### ISSUE TITLE
Microk8s Install

### ISSUE THREAD

**Issue by sh-manish** [mlrun/mlrun#1927]
There are a 2 PVCs in the setup -

1. mlrun-pvc 
2.  mlrun-kit-shared-pvc 

The second one is "pending" on install - and seems like the definition is missing the volume information

This is the same result on Microk8s 1.21 and 1.22

**Comment by Hedingber** [comment]
Hi @sh-manish 👋 
Thanks for reaching out
The `mlrun-kit-shared-pvc` PVC is claiming a `nfs` PV, that PV should be created by the nfs-provisioner we're bringing up as part of this chart. I assume if the PV was not created it means that something went wrong with the nfs-provisioner initialization
Can you do `kubectl get pods` to see what is the pod's status ? `kubectl describe pod <pod-name>` to see more details ? `kubectl logs <pod-name>` to check the logs ?

**Comment by Hedingber** [comment]
No answer for 8 days, closing the issue
Feel free to reopen if you need any more help
