### ISSUE TITLE
Kubernetes install without NodePorts

### ISSUE THREAD

**Issue by CaelumF** [mlrun/mlrun#1945]
Hello

I was following https://docs.mlrun.org/en/stable/install-kubernetes.html and it seems to work great, apart from the NodePorts. Is the mlrun-kit not meant for remote servers? It exposes several services via NodePorts, which obviously aren't secure because they can be accessed by anyone. I deleted the nodeports and will set up a reverse proxy to access these services securely, but each time I change helm values the nodeports will be re-created and if I forget to delete them my cluster could be compromised hehe.

Removing the nodePort values in the yaml seems to have no effect because they are just for changing the nodePort port number from a default. Could it be good to have a simple way to disable creating nodeports?

**Comment by Tankilevitch** [comment]
Hey @CaelumF, Thank you for the question and sorry for the late response.
MLRun is definitely meant to be used for remote servers, by default it's configured to expose itself through node ports as this is the most simple (and the least secure, this is the tradeoff) way of exposing services, but it can be configured differently.
One thing you can do is to configure the k8s services to be of type ClusterIP which means they are only exposed internally to the k8s cluster, this can be done by adding those flags to your helm install command:

```j
# mlrun-api
--set mlrun.api.service.type=ClusterIP \
--set mlrun.api.service.port=8080 \ 
--set mlrun.api.service.targetPort=8080 \
# mlrun-ui
--set mlrun.ui.service.type=ClusterIP \
--set mlrun.ui.service.port=80 \
--set mlrun.ui.service.targetPort=80 \ 
# nuclio-dashboard
--set global.nuclio.dashboard.nodePort=false 
```

There are 4 services exposed by this helm chart, the above command handles 3 of them, and currently handling the 4th Jupyter services is impossible, I will fix the helm chart to be more flexible, in the meanwhile you can workaround it by simply edit the jupyter k8s service( `kubectl -n mlrun edit service mlrun-kit-jupyter`) by changing the type to ClusterIP and removing the `nodePort: 30040`.

There is a bit more advanced option, to use the charts to create [ingresses](https://kubernetes.io/docs/concepts/services-networking/ingress/) for you, here's how it can be done.

```j
# mlrun-api (you need to change to host to available dns in your cluster
--set mlrun.api.ingress.hosts[0].host=mlrun-api.localhost \
--set mlrun.api.ingress.hosts[0].paths={} \
--set mlrun.api.ingress.enabled=true \
# nuclio (same here with the hosts) 
--set nuclio.dashboard.ingress.enabled=true \ 
--set nuclio.dashboard.ingress.hosts={nuclio.localhost} \
# mlrun-ui (same here, and note that it holds extra parameter pointing to nuclio)
--set mlrun.ui.ingress.enabled=true \  
--set mlrun.ui.ingress.hosts[0].paths={} \ 
--set mlrun.ui.ingress.hosts[0].host=mlrun-ui.localhost \
--set mlrun.ui.nuclio.uiURL=nuclio.localhost
```

For the jupyter there isn’t corrently a way to create ingress from the helm but after running the helm you can run the following for creating ingress for jupyter.

`kubectl -n mlrun apply -f jupyter-ingress.yaml` (Make sure you change the host to be relevant for your cluster).

```r
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter
spec:
  ingressClassName: nginx
  rules:
  - host: jupyter.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mlrun-kit-jupyter
            port: 
              number: 8888
```

**Comment by Tankilevitch** [comment]
Here are links for further understanding of all the available configuration to set for each service.

- MLRun API -
    - Service - [https://github.com/v3io/helm-charts/blob/development/stable/mlrun/values.yaml#L19](https://github.com/v3io/helm-charts/blob/development/stable/mlrun/values.yaml#L19)
    - Ingress - [https://github.com/v3io/helm-charts/blob/development/stable/mlrun/values.yaml#L24](https://github.com/v3io/helm-charts/blob/development/stable/mlrun/values.yaml#L24)
- MLRun UI - link
    - Service - [https://github.com/v3io/helm-charts/blob/development/stable/mlrun/values.yaml#L350](https://github.com/v3io/helm-charts/blob/development/stable/mlrun/values.yaml#L350)
    - Ingress - [https://github.com/v3io/helm-charts/blob/development/stable/mlrun/values.yaml#L355](https://github.com/v3io/helm-charts/blob/development/stable/mlrun/values.yaml#L355)
- Nuclio Dashboard -
    - Ingress - [https://github.com/nuclio/nuclio/blob/development/hack/k8s/helm/nuclio/values.yaml#L143](https://github.com/nuclio/nuclio/blob/development/hack/k8s/helm/nuclio/values.yaml#L143)
    - Service - [https://github.com/v3io/helm-charts/blob/development/stable/mlrun-kit/values.yaml#L11](https://github.com/v3io/helm-charts/blob/development/stable/mlrun-kit/values.yaml#L11)  (change to 0 or false to disable nodePort and activate ClusterIP)

**Comment by CaelumF** [comment]
Thanks for the detailed response! thanks as well for the ingress --sets, I'll use them and use ClusterIps instead of NodePorts through the --sets. Creating the ingress for jupyter manually isn't so bad :smile: 

What do you think about having ClusterIps as the default, with example values.yml or example --set flags to have NodePorts?

**Comment by Tankilevitch** [comment]
@CaelumF, I am glad it helped.

The main purpose in the default configuration is to set you up as fast as possible with a working environment so you could experience MLRun and get value from it.
If the default will be ClusterIPs the services will not be accessible and will require deeper knowledge about k8s components and longer setup experience.

Note that the default configuration is not purposed for production usage.

**Comment by CaelumF** [comment]
Fair enough, thanks!
