### ISSUE TITLE
mlrun.get_or_create_project() function throws NotImplementedError

### ISSUE THREAD

**Issue by cpoptic** [mlrun/mlrun#1976]
With `mlrun==0.9.3` installed (the latest as of May 18, 2022, running [the first mlrun basics tutorial notebook](https://docs.mlrun.org/en/latest/tutorial/01-mlrun-basics.html) throws a `NotImplementedError` when trying to call the `mlrun.get_or_create_project()` function:

`project = mlrun.get_or_create_project(project_name_base, context="./", user_project=True)`

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/gstore/home/popticc/miniconda3/envs/irisai/lib/python3.6/site-packages/mlrun/projects/project.py", line 279, in get_or_create_project
>     user_project=user_project,
>   File "/gstore/home/popticc/miniconda3/envs/irisai/lib/python3.6/site-packages/mlrun/projects/project.py", line 205, in load_project
>     project = _load_project_from_db(url, secrets, user_project)
>   File "/gstore/home/popticc/miniconda3/envs/irisai/lib/python3.6/site-packages/mlrun/projects/project.py", line 356, in _load_project_from_db
>     return db.get_project(project_name)
>   File "/gstore/home/popticc/miniconda3/envs/irisai/lib/python3.6/site-packages/mlrun/db/filedb.py", line 465, in get_project
>     raise NotImplementedError()
> NotImplementedError

**Comment by Tankilevitch** [comment]
Hey @cpoptic,
Have you completed the [installation guide](https://docs.mlrun.org/en/latest/install.html)?

**Comment by Tankilevitch** [comment]
It looks that the client you are using is not configured to the MLRun backend; this issue should be resolved after installing MLRun on docker or kubernetes.

**Comment by Hedingber** [comment]
No response, closing
@cpoptic feel free to reopen if you need any more help
