### ISSUE TITLE
Cannot be able to injest data

### ISSUE THREAD

**Issue by mashirali** [mlrun/mlrun#2018]
Got this error from this line -> fstore.ingest(static_fs, static_df)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-dd6b3183cb63> in <module>
      2 
      3 # ingest the static device data
----> 4 fstore.ingest(static_fs, static_df)
      5 
      6 # ingest the device metrics

/opt/conda/lib/python3.8/site-packages/mlrun/feature_store/api.py in ingest(featureset, source, targets, namespace, return_df, infer_options, run_config, mlrun_context, spark_context, overwrite)
    502     featureset.save()
    503 
--> 504     df = init_featureset_graph(
    505         source,
    506         featureset,

/opt/conda/lib/python3.8/site-packages/mlrun/feature_store/ingestion.py in init_featureset_graph(source, featureset, namespace, targets, return_df, verbose, rows_limit)
     53     if graph.engine != "sync":
     54         # todo: support rows_limit it storey sources
---> 55         _add_data_steps(
     56             graph,
     57             cache,

/opt/conda/lib/python3.8/site-packages/mlrun/feature_store/ingestion.py in _add_data_steps(graph, cache, featureset, targets, source, return_df, context)
    180     validate_target_placement(graph, default_final_step, targets)
    181     cache.cache_resource(featureset.uri, featureset, True)
--> 182     table = add_target_steps(
    183         graph, featureset, targets, to_df=return_df, final_step=default_final_step
    184     )

/opt/conda/lib/python3.8/site-packages/mlrun/datastore/targets.py in add_target_steps(graph, resource, targets, to_df, final_step)
    205     for target in targets:
    206         driver = get_target_driver(target, resource)
--> 207         table = driver.get_table_object() or table
    208         driver.update_resource_status()
    209         driver.add_writer_step(

/opt/conda/lib/python3.8/site-packages/mlrun/datastore/targets.py in get_table_object(self)
    928         return Table(
    929             uri,
--> 930             V3ioDriver(webapi=endpoint),
    931             flush_interval_secs=mlrun.mlconf.feature_store.flush_interval,
    932         )

/opt/conda/lib/python3.8/site-packages/storey/drivers.py in __init__(self, webapi, access_key, use_parallel_operations, v3io_client_kwargs)
     75     def __init__(self, webapi: Optional[str] = None, access_key: Optional[str] = None, use_parallel_operations=True,
     76                  v3io_client_kwargs=None):
---> 77         NeedsV3ioAccess.__init__(self, webapi, access_key)
     78         self._v3io_client = None
     79         self._v3io_client_kwargs = v3io_client_kwargs or {}

/opt/conda/lib/python3.8/site-packages/storey/drivers.py in __init__(self, webapi, access_key)
     52         webapi = webapi or os.getenv('V3IO_API')
     53         if not webapi:
---> 54             raise ValueError('Missing webapi parameter or V3IO_API environment variable')
     55 
     56         if not webapi.startswith('[http://'](http://%27%3C/span%3E%3Cspan)[ class="ansi-blue-fg">) and not webapi.startswith('](http://%27%3C/span%3E%3Cspan)https://' class="ansi-blue-fg">):

ValueError: Missing webapi parameter or V3IO_API environment variable

**Comment by Tankilevitch** [comment]
Hey @mashirali, already answered in the community slack, copying answer from there.
The error you ran into is regarding functionality of the enterprise Iguazio platform. 
The default behavior of the Feature Store is to ingest into the V3IO data layer which is only available in the enterprise platform.
The attached notebook example should work on the open source. 
The change is specifying a `ParquetTarget` with a local path during ingestion.
[basic-demo-mlrun-kit.ipynb.zip](https://github.com/mlrun/mlrun/files/8889750/basic-demo-mlrun-kit.ipynb.zip)

Closing issue, feel free to re-open if you have any further question related the topic.
