### ISSUE TITLE
Identity\IDP (Active Directory) - improve role mapping

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2049]
MEDIUM PRIORITY

**Motivation:**
Identity\IDP (Active Directory) - Current setting of security roles required manual changes (on Iguazio side) in case of add new user or in case of change roles for existing users (if default role setting is not enough). It is a complication for bigger company, where IAM/IdM is used because the company typically support hundreds of applications and manual changes can generate mistakes and addition effort for regular company audits (e.g. check of user real roles, segregation of duties, etc.)

**Improvement idea:**
Improve setting of Identity\IDP (Active Directory) - add ability to map Active Directory roles to Iguazio roles (support not only default roles).

> Sample:
>   map active directory role - "ldap://ds.example.com:389/dc=example,dc=com" to Iguazio roles Developer + Data
>   map active directory role - "ldap://ds.example.com:389/dc=example2,dc=com" to Iguazio roles Tenant Admin, Service Admin, ...
>

**Comment by george0st** [comment]
@adiso75, if it makes sense for you, thanks.

**Comment by adiso75** [comment]
@george0st hey- just to clarify, the IDP is part of the platform version and not the MLrun part
we'll take a look at it in the context of the platform
