### ISSUE TITLE
[Installation]: MLRun locally using Docker 

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2191]
### Installation check

- [X] I have read the [installation guide](https://docs.mlrun.org/en/latest/install.html).

### Installation OS

Mac

### Installation Method

Docker

### Kubernetes Cluster Type

Kubernetes for Docker Desktop

### MLRun Kit Helm Chart Version

image: "mlrun/jupyter:${TAG:-1.0.2}"

### Issue Description

My colleague install 'MLRun locally using Docker' via 'compose.with-jupyter.yaml' (on Mac Power M1) and he got empty screen after click to the project in MLRun GUI. See detail in attachment

### Installation Logs

<details>

Replace this line with the installation logs.

</details>
[fstoreerror.docx](https://github.com/mlrun/mlrun/files/9208227/fstoreerror.docx)

**Comment by george0st** [comment]
[fstoreerror.docx](https://github.com/mlrun/mlrun/files/9208555/fstoreerror.docx)

**Comment by nschenone** [comment]
Hi @george0st thanks for reporting this. Just want to confirm the version of MLRun that is running. Can you please paste the output of `docker ps | grep mlrun`? Thanks

**Comment by nschenone** [comment]
There are some known bugs in the current `docker-compose` installation that are being worked on. For now, we recommend using the K8s installation found [here](https://docs.mlrun.org/en/latest/install/kubernetes.html). Thanks

**Comment by george0st** [comment]
Hi @nschenone thanks, we try to deliver output from "docker ps". 

It is much easier to use docker-compose for us. From time to time in case to use standard installation way (via "helm --namespace mlrun install ..."), is problem to run correctly all services (we checked it via "kubectl get pods -n mlrun").

BTW: We caught one issue that running `docker-compose` from powershell is problematic, but running via standard cmd (command line) works fine (we tried it on a Mac Power M1)

**Comment by george0st** [comment]
Outputs from "docker ps" are:

8a80612a3855   mlrun/jupyter:1.0.2                     "tini -g -- /bin/bas…"   13 days ago      Up 22 hours             0.0.0.0:8080->8080/tcp, 0.0.0.0:8888->8888/tcp   downloads_jupyter_1

b7f0e9f78913   mlrun/mlrun-ui:1.0.2                    "/docker-entrypoint.…"   13 days ago      Up 22 hours             0.0.0.0:8060->80/tcp                             downloads_mlrun-ui_1
