### ISSUE TITLE
[Bug]: ParquetTarget with default name (in docker composer)

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2238]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of the MLRun Kit.

### Reproducible Example

```python
import mlrun
import mlrun.projects as prj
import mlrun.feature_store as fstore

project_name="steuer01-compose"
project = mlrun.get_or_create_project(project_name,context='./', user_project=False)

# generate error 'Access key must be provided in Client() arguments or in the V3IO_ACCESS_KEY environment variable'
pt=mlrun.datastore.ParquetTarget(path='./tmp/tst/')

# OK
#pt=mlrun.datastore.ParquetTarget(name='tst',path='./tmp/tst/')
# OK
#pt=mlrun.datastore.CSVTarget("mycsv", path="./aaa/new_stocks.csv")

feature_set = fstore.FeatureSet("stocks02", entities=[fstore.Entity("fn0"),fstore.Entity("fn1")])
feature_set.set_targets(targets=[pt],with_defaults=False)

from mlrun.datastore.targets import ParquetTarget,CSVTarget
import numpy as np
import pandas as pd
import sys
import time

df=pd.DataFrame(np.random.randint(90000000000, size=(100,10)), columns=[f"fn{i}" for i in range(10)])
print('Size for Offline is: ' + str(round(sys.getsizeof(df)/(1024*1024),2)) + ' Mbytes, Rows = ' + str(len(df)))

print(df.head(3))

#it generate 'ValueError: Access key must be provided in Client() arguments or in the V3IO_ACCESS_KEY environment variable'
fstore.ingest(feature_set,df)
```

### Issue Description

Issue in env. docker compose, during ingestion where ParquetTarget contains name=''

Detail:
- if name is '' for ParquetTarget then it generate error during ingestion see '**Access key must be provided in Client() arguments or in the V3IO_ACCESS_KEY environment variable**' in environment docker compose (it is without setting of V3IO_ACCESS_KEY )

- if name is different '' for ParquetTarget then all is fine

### Expected Behavior

It will be possible to use empty name for ParquetTarget (only change path to local directory) and use it for data ingestion in docker compose (without error about V3IO_ACCESS_KEY).

### Python Version

3.8.8 (default version for MLRun 1.0.2)

### MLRun Version

1.0.2 (installation via 'compose.with-jupyter.yaml')

### Additional Information

This issue will exist probably only with docker compose (with setting only variable MLRUN_DBPATH)

sample see attached jupyter notebook (only remove suffix '.txt')
[JIST_000 (3).ipynb.txt](https://github.com/mlrun/mlrun/files/9279848/JIST_000.3.ipynb.txt)

**Comment by Tankilevitch** [comment]
Hi @george0st, apologies for the late response.
Thank you for reporting the bug, it appears like a wrong handling of an empty named targets.

Looking at the stack trace of the attached notebook, is it the full stack trace?

Workaround is to set `name=x` when creating the target.

**Comment by george0st** [comment]
Hi @Tankilevitch, do not apologize, I calculate with focus on issues in slow mode (really fine for me). 

Current bug is not critical and the workaround is simple as you wrote. 

Yes, the notebook contains full stack trace.

BTW: Can you close the bug after solving of that (in the next release/revision)?

**Comment by Tankilevitch** [comment]
Thank you @george0st , will update when resolved.

**Comment by george0st** [comment]
@Tankilevitch, the mistake is not in version 1.0.6. I will close this bug.
