### ISSUE TITLE
[Docs]: Add documentation for mlrun.feature_store.feature_set.FeatureSetStatus

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2313]
### MLRun Kit version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://docs.mlrun.org/en/latest/)

### Location of the documentation

`https://docs.mlrun.org/en/latest/api/mlrun.feature_store.html#mlrun.feature_store.FeatureSet.status`

### Documentation problem

Missing documentation for this class (it is without generation of documentation but some parts of source code contains relevant documentation)

### Suggested fix for documentation

Please, generate documentation also for this class

**Comment by theSaarco** [comment]
Fixed in #2357
