### ISSUE TITLE
[Bug]: `get_online_feature_service` fails with "ValueError: substring not found' when column begin with "aggr_"	

### ISSUE THREAD

**Issue by jillnogold** [mlrun/mlrun#2315]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of the MLRun Kit.

### Reproducible Example

```python
See zip in Issue Description
```

### Issue Description

Fails to return online feature vector, ends with error message:

```
[error] Pushing error to error stream: substring not found

...

ValueError: substring not found
```
[ZfwPDWHvUt.zip](https://github.com/mlrun/mlrun/files/9442317/ZfwPDWHvUt.zip)

### Expected Behavior

expect expect to receive online feature vector

### Python Version

3.8

### MLRun Version

1.0.4

**Comment by Tankilevitch** [comment]
This happens because columns named `_` or `aggr_` are reserved for internal use.
Suggested solution is to change the column name, for more information: https://docs.mlrun.org/en/latest/feature-store/feature-sets.html#ingest-data-into-the-feature-store
