### ISSUE TITLE
[Bug]: code_to_function fails when filename contains special characters

### ISSUE THREAD

**Issue by jillnogold** [mlrun/mlrun#2321]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of the MLRun Kit.

### Reproducible Example

```python
see attachment in Issue Description
```

### Issue Description

[code_to_function-fails.zip](https://github.com/mlrun/mlrun/files/9459162/code_to_function-fails.zip)

deploying a simple function using mlrun.code_to_function() fails when filename contain special characters like space or parenthesis.

### Expected Behavior

mlrun.code_to_function() completes

### Python Version

3.8

### MLRun Version

 1.0.0

**Comment by jillnogold** [comment]
internal ticket: https://jira.iguazeng.com/browse/ML-1584


























































xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jillg/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jillg/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



https://github.com/mlrun/mlrun/issues/2321
--




</body>

</html>





























































](https://jira.iguazeng.com/browse/ML-1584)

**Comment by alonmr** [comment]
ticket is closed
