### ISSUE TITLE
[Docs]: Improve description of the CONTRIBUTING.md for new tests (in case of add new code/function)

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2369]
### MLRun Kit version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://docs.mlrun.org/en/latest/)

### Location of the documentation

[see file CONTRIBUTING.md in ](https://github.com/mlrun/mlrun/blob/development/CONTRIBUTING.md)

### Documentation problem

It would be very useful to add bigger detail for add new tests and testing new custom added functions.

1] E.g. add preconditions, bigger detail for 'make test-dockerized'. I run current 'make test-dockerized' and I got:

```
python ./automation/version/version_file.py --mlrun-version 0.0.0+unstable
INFO:version_file:Writing version info to file: {'version': '0.0.0+unstable', 'git_commit': 'c6ebb8390dfc56efaf6cf61f4370d94b0f1346c5'}
docker build \
                --file dockerfiles/test/Dockerfile \
                --build-arg MLRUN_PYTHON_VERSION=3.7.13 \
                --build-arg MLRUN_PIP_VERSION=22.0.0 \
                 \
                 \
                --tag mlrun/test: .
invalid argument "mlrun/test:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [build-test] Error 125


```
2] in case of run 'make test-system', addition detail will be useful, I got this issue (and I defined 'MLRUN_DBPATH: http://localhost:8080' in env.yaml (for testing solution in docker compose)

```
MLRUN_SYSTEM_TESTS_CLEAN_RESOURCES=true python -m pytest -v \
                --capture=no \
                --disable-warnings \
                --durations=100 \
                -rf \
                "tests/system"
'MLRUN_SYSTEM_TESTS_CLEAN_RESOURCES' is not recognized as an internal or external command,
operable program or batch file.
make: *** [test-system] Error 1

```

### Suggested fix for documentation

Add addition detail to CONTRIBUTING.md

**Comment by Tankilevitch** [comment]
Thank you @george0st for pointing this out! 
I'll add more information for developers on how to use our internal testing tools.
Will through a ping in this issue once added.

**Comment by george0st** [comment]
Updated CONTRIBUTING.md
