### ISSUE TITLE
[Bug]: Ingestion issue with pandas engine (and ParquetTarget path)

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2424]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of the MLRun Kit.

### Reproducible Example

```python
import time
import numpy as np
import pandas as pd
import mlrun
import mlrun.feature_store as fstore
from mlrun.datastore.targets import ParquetTarget,CSVTarget

prediction_set = fstore.FeatureSet("fs_predcitors", 
                                 entities=[fstore.Entity("id")], 
                                 description="Predictors set")
                                 engine="pandas")


prediction_set.graph\
    .to(name="date_transformation", handler=date_transform)\
    .to(name="Aggregations", handler=aggr_transform)\
    .to(name="One-hot encoding", handler=encode)

prediction_set.set_targets(with_defaults=False, targets=[ParquetTarget(name = 'fs_of', path='PE_data/targets')])

prediction_set.plot(with_targets=True)

pred_df = fstore.ingest(prediction_set, data)
```

### Issue Description

Bug during ingestion see 
`IsADirectoryError: [Errno 21] Is a directory: '/home/jovyan/Practical_Exercises_202209/PE_data/targets/1663693744331_729'`

Full sample see attached jupyter notebook with call stack (Edmond from Iguazio confirmed that it is a bug).

[Practical_Excercises_03a_addition.ipynb.txt](https://github.com/mlrun/mlrun/files/9617937/Practical_Excercises_03a_addition.ipynb.txt)

### Expected Behavior

Will be possible to ingest data also in pandas engine with path as directory (see ParquetTarget)

### Python Version

3.8.8

### MLRun Version

1.1.0

### Additional Information

Tested in docker compose

**Comment by gtopper** [comment]
This notebook – [Practical_Exercises_01.ipynb.txt](https://github.com/mlrun/mlrun/files/9623941/Practical_Exercises_01.ipynb.txt) – needs to be run before [Practical_Excercises_03a_addition.ipynb.txt](https://github.com/mlrun/mlrun/files/9617937/Practical_Excercises_03a_addition.ipynb.txt) in order to reproduce the issue.
