### ISSUE TITLE
[Bug]: Off-line feature vector (issue with time filter)

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2426]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of the MLRun Kit.

### Reproducible Example

```python
# Define the Feature Vector name (viz.5.2)
feature_vector_name = 'fv_join'

# Import the Parquet Target so we can directly save our dataset as a file
from mlrun.datastore.targets import ParquetTarget

# Get offline feature vector. We will return a pandas dataframe.
fv_join_offline_2 = fstore.get_offline_features(feature_vector_name, target=ParquetTarget(name = 'v_join', path='PE_data/vectors/fv_df2.parquet'), 
                                                entity_timestamp_column = 'date_base',
                                                start_time = '2019-01-01 00:00:00',
                                                end_time = '2021-10-31 00:00:00')


df_join_fv_offline_2 = fv_join_offline_2.to_dataframe()
print(df_join_fv_offline_2.shape)
df_join_fv_offline_2.head()
```

### Issue Description

Off-line feature vector with time filter does not work (the output is empty data frame).

See full sample in attached jupyter notebook (!!! before start code from Jupyter, you have to create directory PE_data, the rest of files such as csv, etc. will be generated automatically from jupyter notebook !!!).

[Practical_Exercises_01.ipynb.txt](https://github.com/mlrun/mlrun/files/9619061/Practical_Exercises_01.ipynb.txt)

Issue is here in chapter 5.2.1.1 see picture:
![MicrosoftTeams-image (23)](https://user-images.githubusercontent.com/95856749/191572791-ee6aba87-b376-48d0-ad06-59c4762c8d66.png)

BTW: Preview chapter 5.2.1 return all data from the same feature vector, without time filter and it work correctly, see picture:
![image](https://user-images.githubusercontent.com/95856749/191573915-2c38f4d7-a24b-440e-a703-adea5a52f6e4.png)
 

### Expected Behavior

Off-line feature vectore with time filter will return dataframe with relevant items/rows (not empty dataframe)

### Python Version

3.8.8

### MLRun Version

1.1.0

### Additional Information

Tested in docker compose (with Jupyter notebook).

**Comment by gtopper** [comment]
Hi @george0st, I ran the attached notebook, and I think that changing this line
```
source = CSVSource("source_df2", path=fs_2_source, parse_dates = ['date_base', 'date_event'])
```
to
```
source = CSVSource("source_df2", path=fs_2_source, parse_dates = ['date_base', 'date_event'], time_field="date_base")
```
fixes the issue. WDYT?

**Comment by george0st** [comment]
Hi @gtopper, I got work-around from @EdmondIguazio (but adding only time_field was not enough).
