### ISSUE TITLE
[Feature Request]: Add complex tests to MLRun also

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2427]
### Feature Type

- [X] Adding new functionality to MLRun

- [x] Changing existing functionality in MLRun

- [x] Removing existing functionality in MLRun

### Problem Description

What?
Improve quality of tests. 

Why?
I think, current MLRun tests in GIT, do not cover bigger E2E tests and tested only smaller part of separate codes, based on that new MLRun version can contain e.g. these issues see e.g. https://github.com/mlrun/mlrun/issues/2426 or https://github.com/mlrun/mlrun/issues/2424

### Feature Description

Add to the tests complex samples also and establish different level of tests as part of CI/CD e.g. tests with different complexity:

- Unit tests (test interfaces, version compatibility, ...)
- Function tests (test basic and isolated functions, ...)
- Integration tests (test connection to different sources e.g. snowflake, cloudera, kafka, etc.)
- E2E tests (build heavy, complex tests with integration and based on typical customer use cases, etc.)

Sample little bigger not pure end2end tests, see attached jupyter notebooks:
[Practical_Exercises_01.ipynb.txt](https://github.com/mlrun/mlrun/files/9619248/Practical_Exercises_01.ipynb.txt)
[Practical_Excercises_03a_addition.ipynb.txt](https://github.com/mlrun/mlrun/files/9619249/Practical_Excercises_03a_addition.ipynb.txt)

### Alternative Solutions

Accept effort for bug fixing

### Additional Context

n/a

**Comment by liranbg** [comment]
Hi @george0st - MLRun's complexity tests indeed need some better transparency for newcomers (and contributions such as you). Thing is, that behind the open-source community and tests running on GIT - there is a whole QA team running manual and automation tests, that, as I am sure you assume, are not running here (I'm just putting this piece of information here for other people who are uncertain).

On top of that, in MLRun we have few test suites that runs
- Unit
- Integration (Open source)
- System Test (More like E2E with Iguazio's)

The latter runs manually, by the MLRun core team (managers, feature owners, etc) and have dedicated suites for that (@Tankilevitch  might elaborate where they exists).

For features such as you suggested, I truly believe we should open up the integration test for broad use-cases and provide a subset suite for complex cases which should run upon-release or periodically. mainly for sanity.

We (MLRun dev & core team) are working on making both contributing and testing/debugging more transparent for new developers and users. It might take some time, but the end-goal, is, as you suggested, be able to have more test cases and clear understanding of how & where to add tests when developing a feature to MLRun.


One thing I am not quiet sure about your proposal is

> Accept effort for bug fixing

Bug fixes are always welcome and accepted. Perhaps we are talking about something more broad here?

**Comment by george0st** [comment]
Hi @liranbg, perfect, we look at it the same way (I am only looking for the way for improvement). The sentence "Accept effort for bug fixing" was only note for question "Alternative Solutions?", you can really forget about it.
