### ISSUE TITLE
Issue in installing MLRun locally on windows

### ISSUE THREAD

**Issue by ganesh3** [mlrun/mlrun#2464]
Hi,

I am following instructions to install MLRun locally on Windows 10 as described in page /install/local-docker.html with jupyter image.

set HOST_IP=localhost
set SHARED_DIR=D:\MLRun
mkdir  %SHARED_DIR%
docker-compose -f compose.with-jupyter.yaml up results **in below error.**

_invalid interpolation format for services.jupyter.volumes.[].
You may need to escape any $ with another $.
required variable SHARED_DIR is missing a value: err_

**Comment by Tankilevitch** [comment]
Hey @ganesh3 nice to meet you!

seems like for some reason the docker-compose isn't able to find `SHARED_DIR` environment variable.
can you please provide the following:
`echo %SHARED_DIR%`?

**Comment by ganesh3** [comment]
Getting the below response even after setting the SHARED_DIR on terminal.

(base) PS D:\MLRun> echo %SHARED_DIR%
%SHARED_DIR%

**Comment by Tankilevitch** [comment]
So it did catched the %SHARED_DIR% when creating the directory, but didn't catch it when running the docker-compose correct? 

Are you using powershell? It is different from windows.
Did you run it all as one command or separated?

**Comment by ganesh3** [comment]
Yes, that's correct. I am running it on Windows Terminal.

**Comment by Tankilevitch** [comment]
I am not sure why setting the environment variable isn't working for you.
But for now just to continue to work you can edit the compose file and replace all occurrences of `${SHARED_DIR:?err}` with   `D:\MLRun`that should do the work.

**Comment by Tankilevitch** [comment]
Closing for now, @ganesh3 feel free to open back if you experience any issues regarding running the `docker-compose` command.
