### ISSUE TITLE
[Bug]: mlrun.runtimes.utils.RunError: function image is not built/ready, use .deploy() method first

### ISSUE THREAD

**Issue by mashirali** [mlrun/mlrun#2479]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of the MLRun Kit.

### Reproducible Example

```python
When i run the function, this error comes. So when i do fn.deploy(), this gives me error of a not successfull run for deployment.
```

### Issue Description

Function Deployment error

### Expected Behavior

it should run the function

### Python Version

3.7

### MLRun Version

latest

**Comment by Tankilevitch** [comment]
Hi @mashirali, what is the stuck trace you receive when running `.deploy()`?
Also, are you using the helm-chart installation or the docker-compose one?

If possible please attach the reproducible code
