### ISSUE TITLE
[Feature Request]: Use python 3.9 as default

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2481]
### Feature Type

- [X] Adding new functionality to MLRun

- [X] Changing existing functionality in MLRun

- [X] Removing existing functionality in MLRun

### Problem Description

It would be fine to use python 3.9 as default.

Current installation of MLRun (1.1.0) contains python version 3.7.6 (in Enterprise version) and 3.8.8 (in Free version), if you fully support 3.9 (I catched this info a few times), please update default installation to 3.9

### Feature Description

Use python 3.9 as default with relation to relevant components (version update will be needed).

BTW: It will have impact to vulnerability check also.

### Alternative Solutions

n/a

**Comment by Tankilevitch** [comment]
Hey @george0st, this is in on our road map to upgrade the default python version. 
@quaark is working on adding CI mechanism which will release mlrun images with newer python versions, it will take some time to change the default as it will require to fully validate dependencies and compatibility before we change the default mlrun python version that our images are running with.

**Comment by george0st** [comment]
relation to #2567
