### ISSUE TITLE
[Bug]: Problem with visualization of project content in Safari browser

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2502]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of the MLRun Kit.

### Reproducible Example

```python
It is possible to see list of project, but after click to the project, the project details (FeatureStore, ...) is not visible.

It seems like issue with Safari browser (in MacOS) version 16.0 (17614.1.25.9.10, 17614)
BTW: It works correctly under Chrome and Edge.
```

### Issue Description

Problem with visualization in Safari

### Expected Behavior

It is possible to use Safari browser also.

### Python Version

3.7.6

### MLRun Version

1.1.0

### Additional Information

see attachment
![MicrosoftTeams-image (40)](https://user-images.githubusercontent.com/95856749/196676593-1caa77d3-fb82-4db2-bdd5-4a16ac6e6895.png)

**Comment by Tankilevitch** [comment]
Hey @george0st , we support running MLRun on chrome and firefox latest versions, we do not support running on safari at the moment. Is this blocking you from working on MLRun?

**Comment by george0st** [comment]
Hi @Tankilevitch, I am totally fine with support chrome and firefox (and it is enough), but I did not see these limits in documentation (I checked https://www.iguazio.com/docs/latest-release/release-notes/ and also https://docs.mlrun.org/en/latest/index.html ). Please can you mention this browser support in documentation (colleagues from different team with MacOS use Safari as default browser).

**Comment by gilad-shaham** [comment]
@jillnogold please see what's the best place to add it. I don't think we have a software specification page in docs.mlrun.org, so we may need to write one.
