### ISSUE TITLE
[Bug]: Bump pydantic 1.10.2

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2503]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of the MLRun Kit.

### Reproducible Example

```python
import mlrun
import mlrun.feature_store as fstore
from mlrun.datastore.sources import CSVSource, ParquetSource, HttpSource

project_name = 'ste-test'
project = mlrun.get_or_create_project(project_name, context='./', user_project=False)

#... it generates
~/.pythonlibs/steuer-jupyter/lib/python3.7/site-packages/pydantic/__init__.cpython-37m-x86_64-linux-gnu.so in init pydantic.__init__()

~/.pythonlibs/steuer-jupyter/lib/python3.7/site-packages/pydantic/dataclasses.cpython-37m-x86_64-linux-gnu.so in init pydantic.dataclasses()

ImportError: cannot import name dataclass_transform
```

### Issue Description

Bump pydantic 1.10.2, pydantic==1.9.2 is correct
see also https://support.iguazio.com/portal/en/ticket/251179000016909003

### Expected Behavior

update requierements.txt

### Python Version

3.7.6

### MLRun Version

1.1.0

### Additional Information

see also https://support.iguazio.com/portal/en/ticket/251179000016909003

**Comment by Tankilevitch** [comment]
Hey @george0st, what pip version is installed on your work environment? 
We encountered this issue as well when using old pip version, which for some reason unable to resolve and upgrade underlying of underlying dependencies. 
If that is the situation please make sure your pip version is set to the latest before installing mlrun.

If running in conda: 
```
$CONDA_HOME/bin/conda update -y conda
$CONDA_HOME/bin/conda install pip==22.2.2 -y
```

**Comment by george0st** [comment]
I used pre-installed pip version from Jupyter (MLRun Enterprise version 3.5.1 contains pip==20.2.4 and python 3.7.6). Positive point, after upgrade pip to the version 22.3, it partly helps (different type of error, but without the issue with pydantic 1.10.2)

A few ideas for improvement (what do you think?):
 - upgrade default installation of Jupyter (use the last pip version)
 - add to the requirement.txt pip>=22.2.2

**Comment by Tankilevitch** [comment]
@george0st,
We will upgrade the default pip version in newer jupyters, but we are unable to do this to already released jupyter versions.
Regarding adding pip requirement to mlrun this sounds like a good idea, we will have to test it.
**Thanks a Lot** for the suggestions!!

Closing issue.
