### ISSUE TITLE
[Bug]:  Project gets error when running a workflow whose project has init_git=True. 

### ISSUE THREAD

**Issue by jillnogold** [mlrun/mlrun#2621]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of the MLRun Kit.

### Reproducible Example

```python
see [2637.zip](https://github.com/mlrun/mlrun/files/10069382/2637.zip)
```

### Issue Description

Git updated their security management that cause this issue - more information in this  [link](https://stackoverflow.com/questions/71901632/fatal-error-unsafe-repository-home-repon-is-owned-by-someone-else) 

That update affects mlrun when you trying to run a workflow and you are working on a project with init_git=True (context directory is a git directory).

That is because when mlrun tries to load or create a project with init_git=TRUE, MLRun Creates a git repo or uses an existing one and saves the repo object in the project.spec.repo - after that when MLRun tried to run a workflow MLRun tried to execute self.spec.repo.is_dirty() command but it failed, and cause the workflow to fail.

### Expected Behavior

Project should run without error

### Python Version

3.7.6

### MLRun Version

1.1.0

### Additional Information

[internal issue ML-2637](https://jira.iguazeng.com/browse/ML-2637)
[2637.zip](https://github.com/mlrun/mlrun/files/10069382/2637.zip)

**Comment by Tankilevitch** [comment]
Hey, 
This can be resolved by running the following:
`git config --global --add safe.directory '*'` ( instead of * you can set specific directory ).
