### ISSUE TITLE
[Bug]: Max retries exceeded with url: /v2/models/cancer-classifier/infer

### ISSUE THREAD

**Issue by j0terry** [mlrun/mlrun#2716]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of the MLRun Kit.

### Reproducible Example

```python
original 01-mlrun-basics.ipynb, issues see attached jupyter notebook, you can see this error in case of call serving_fn.invoke("/v2/models/cancer-classifier/infer", body=my_data)
```

### Issue Description

in case of call `serving_fn.invoke("/v2/models/cancer-classifier/infer", body=my_data)` I got 

`OSError: error: cannot run function at url http://127.0.0.1:54652/v2/models/cancer-classifier/infer, HTTPConnectionPool(host='127.0.0.1', port=54652): Max retries exceeded with url: /v2/models/cancer-classifier/infer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f175c75b070>: Failed to establish a new connection: [Errno 111] Connection refused'))`

see jupyter
[Uploading 01-mlrun-basics.ipynb.txt…]()

### Expected Behavior

Invoke without this issue, it can have relation to https://github.com/mlrun/mlrun/issues/2102

### Python Version

3.8.8

### MLRun Version

1.2.0

**Comment by harishgawade1999** [comment]
getting same error

**Comment by harishgawade1999** [comment]
Hello @j0terry...have u solved this issue?

**Comment by j0terry** [comment]
@harishgawade1999 , I used different UI (PyCharm) and compose.yaml and I got the same issue 👎

**Comment by yaronha** [comment]
@j0terry i just tested it on my windows machine and it worked with 1.2.0, did you set the `HOST_IP` var before running compose?

BTW I did have a failure in the deployment of the function, had to set the `SHARED_DIR` value to the Pseudo-Linux-Style of the dir (`/c/mlrun-data` vs `c:\mlrun-data)

**Comment by george0st** [comment]
@yaronha , I used relevant HOST_IP, I am using this setting:

set HOST_IP=127.0.0.1
set SHARED_DIR=c:\mlrun-data
mkdir %SHARED_DIR%
docker-compose -f "c:\mlrun\compose.with-jupyter.yaml" up

plus I updated version in YAML file to the 1.2.0 and everything works, only last command in tutorial failed.

BTW: Did you tuned it, here https://github.com/mlrun/mlrun/pull/2768 ?

**Comment by yaronha** [comment]
> @yaronha , I got the same issue and I used relevant HOST_IP, I am using this setting:
> 
> set HOST_IP=127.0.0.1 set SHARED_DIR=c:\mlrun-data mkdir %SHARED_DIR% docker-compose -f "c:\mlrun\compose.with-jupyter.yaml" up
> 
> plus I updated version in YAML file to the 1.2.0 and everything works, only last command in tutorial failed.
> 
> BTW: Did you tuned it, here #2768 ?

![image](https://user-images.githubusercontent.com/6298833/207957737-e8c7dba9-64f7-4b97-acf1-54a094862df7.png)

you can see the error you had was: `OSError: error: cannot run function at url http://127.0.0.1:54652...` it cannot reach the address due to the wrong 127.0.0.1 address setting , in my case the address was the host IP (192.168.0.182)

**Comment by j0terry** [comment]
@yaronha , it works, thanks for help

**Comment by harishgawade1999** [comment]
Hello @j0terry can u please help me regarding this...im still getting same error.
