### ISSUE TITLE
[Installation]: Install MLRun on minikube

### ISSUE THREAD

**Issue by TRINHHOANGANH** [mlrun/mlrun#2817]
### Installation check

- [X] I have read the [installation guide](https://docs.mlrun.org/en/latest/install.html).

### Installation OS

Linux

### Installation Method

Kubernetes

### Kubernetes Cluster Type

Kubernetes for Docker Desktop

### MLRun CE Version

0.5.0

### Issue Description

When I install MLRun on minikube, I am trying many times but it don't pull mlrun-jupyter image.
![image](https://user-images.githubusercontent.com/83366198/209543622-f18b254e-1d1c-41b4-af03-c7b38bdeb561.png)
![image](https://user-images.githubusercontent.com/83366198/209543650-361f374d-e1a0-4915-b6d7-c2fd9454901f.png)

Please give me your explain and solution for this

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

### Additional Information

kubectl version: v1.25.3

**Comment by liranbg** [comment]
Hi @TRINHHOANGANH  - can you please share the output of `kubectl -n mlrun describe deployment mlrun-jupyter -o json` and paste it here?

**Comment by TRINHHOANGANH** [comment]
@liranbg, Thank for your reply
I am trying this command -o json but error unknown shorthand flag: 'o'. However I save description to file text.
[error.txt](https://github.com/mlrun/mlrun/files/10305151/error.txt)

**Comment by Tankilevitch** [comment]
Hi @TRINHHOANGANH , can you try pulling the image manually - `docker pull quay.io/mlrun/jupyter:1.1.1` see if it works, if yes then try to helm install again. This could be due to size of the image and internet speed which causes the image not to be fully pulled in the 960s timeout.

LMK if that worked.

**Comment by TRINHHOANGANH** [comment]
@Tankilevitch Thanks !!!
