### ISSUE TITLE
[Docs]: Add summary about new major releases

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2838]
### MLRun Kit version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://docs.mlrun.org/en/latest/)

### Location of the documentation

This information is not available right now

### Documentation problem

It will be useful to publish for new **major** releases (such as MLRun 1.1, 1.2, 1.3, ...) short summary of key changes/benefits (maximal 10 points). 

### **Motivation**
Release nodes for major versions can contain e.g. tens or hundreds small changes (e.g. https://github.com/mlrun/mlrun/releases/tag/v1.2.1-rc9) with impact to MLRun, UI, Storey, Funtions, etc. (and delivery cycle is about 1-3 months). From time to time, It is hard to identify coverage/solving of whole area (e.g. full support Spark engine, because part is about ingestion, second is about pipelines, third is about ...). 

### **Detail**
It will be enough to provide only simple high-level view with link to detail (from GIT), sample:

**MLRun CE - 1.2.0**
- full support Spark engine (for pipelines, ingestion, ...)
- new sources (support confluence Kafka, Redis, etc.)
- new protocols (AVRO, protobuf, etc.)
- ...
- detail see (https://github.com/mlrun/mlrun/releases/tag/v1.2.0, https://github.com/mlrun/mlrun/releases/tag/v1.2.1)

**Comment by gilad-shaham** [comment]
This will be addressed by #2693, it was originally intended to be with MLRun 1.2.0, but was postponed to 1.2.1

**Comment by george0st** [comment]
Many thanks, this information is in documentation right now,
