### ISSUE TITLE
Error not raised when model not found with serving

### ISSUE THREAD

**Issue by nicklausbrown** [mlrun/mlrun#291]
https://github.com/mlrun/mlrun/blob/dea41441f77e47f87edf316e972b042e46bfa22c/mlrun/runtimes/serving.py#L164

HTTPHandler.get_model() returns a Response object when it doesn't find the model name requested in the models. This is a problem because it causes PredictHandler to fail in a cryptic way saying that Request object has no method "preprocess" [line 261](https://github.com/mlrun/mlrun/blob/dea41441f77e47f87edf316e972b042e46bfa22c/mlrun/runtimes/serving.py#L261). This could easily be fixed by checking the return type from get_model() and return immediately if it is of type Response. Probably a more elegant way to do it too.

**Comment by yaronha** [comment]
@nicklausbrown thanks, that is already fixed in 0.4.8 (will release in few days)
