### ISSUE TITLE
[Bug] Unsupported store scheme

### ISSUE THREAD

**Issue by TRINHHOANGANH** [mlrun/mlrun#3028]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of MLRun CE.

### Reproducible Example

```python
End to end image classification workflow
```

### Issue Description

Hi,
when i run the run_function function. I get the error like below image.
![image](https://user-images.githubusercontent.com/83366198/215847379-8255385e-8700-48cf-86bd-45a3c2a19832.png)
Please give me your solution

### Expected Behavior

![image](https://user-images.githubusercontent.com/83366198/215846226-aefff111-9e23-419b-b1f9-8b182ffa4486.png)

### Installation OS

Linux

### Installation Method

Kubernetes

### Python Version

3.9.5

### MLRun Version

1.1.1

**Comment by Tankilevitch** [comment]
Hey @TRINHHOANGANH , It seems like currently MLRun doesn't support reading from other windows drivers than (C:/ and D:/). Please try using `C:/` or `D:/` and let me know if that solves the issue for you.

I've added a requirement for us to add support for all possible windows drivers.

**Comment by yaelgen** [comment]
Hey @TRINHHOANGANH,
This has been fixed in 1.3.0-rc and will be included in the mlrun 1.3.0 official release, which will be available very soon.
Stay tuned, and thank you for bringing this to our attention!
