### ISSUE TITLE
[Feature Request]: Add description for RedisNoSqlTarget and KafkaTarget

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#3041]
### Feature Type

- [X] Adding new functionality to MLRun

- [X] Changing existing functionality in MLRun

- [X] Removing existing functionality in MLRun

### Problem Description

Current documentation is without description of classes for RedisNoSqlTarget and KafkaTarget (see also [mlrun.datastore](https://docs.mlrun.org/en/latest/api/mlrun.datastore.html))

### Feature Description

Add documentation for RedisNoSqlTarget and KafkaTarget (part of these sources are mentioned in change log also)

### Alternative Solutions

n/a

**Comment by jillnogold** [comment]
[RedisNoSql](https://docs.mlrun.org/en/latest/data-prep/ingest-data-fs.html#redis-target-store) is in the docs already.

**Comment by george0st** [comment]
Hi @jillnogold , thx but this [link](https://docs.mlrun.org/en/latest/data-prep/ingest-data-fs.html#redis-target-store) contains only basic information and in the location [data source](https://docs.mlrun.org/en/latest/data-prep/ingest-data-fs.html#redis-target-store) you can see really bigger detail for e.g. ParquetTarget (with view to the description of parameters, info about support different engines, sample, etc.). 

I think all *Targets deserve a full description (it is key part of FeatureStore).
