### ISSUE TITLE
fix auto-doc issues

### ISSUE THREAD

**Issue by yaronha** [mlrun/mlrun#335]
fix auto documentation bugs:
- when the type hint is from a module type is not set: e.g.:
```
import mlrun

def my_func(context, data: mlrun.DataItem):
...
```

- getting error e.g. when there are more than one class in the doc 
```
~/.pythonlibs/jupyter/lib/python3.6/site-packages/mlrun/funcdoc.py in find_handlers(code, handlers)
    232     visitor = ASTVisitor()
    233     visitor.visit(mod)
--> 234     funcs = [ast_func_info(fn) for fn in visitor.funcs]
    235     if handlers:
    236         return [f for f in funcs if f['name'] in handlers]
~/.pythonlibs/jupyter/lib/python3.6/site-packages/mlrun/funcdoc.py in <listcomp>(.0)
    232     visitor = ASTVisitor()
    233     visitor.visit(mod)
--> 234     funcs = [ast_func_info(fn) for fn in visitor.funcs]
    235     if handlers:
    236         return [f for f in funcs if f['name'] in handlers]
~/.pythonlibs/jupyter/lib/python3.6/site-packages/mlrun/funcdoc.py in ast_func_info(func)
    167     if defaults:
    168         for param, default in zip(params[-len(defaults):], defaults):
--> 169             param['default'] = ast_code(default)
    170 
    171     out = func_dict(
~/.pythonlibs/jupyter/lib/python3.6/site-packages/mlrun/funcdoc.py in ast_code(expr)
    282         children += [f'{k.arg}={ast_code(k.value)}' for k in expr.keywords]
    283         inner = ', '.join(children)
--> 284         return f'{expr.func.id}({inner})'
    285     else:  # Leaf (number, str ...)
    286         return repr(getattr(expr, expr._fields[0]))
AttributeError: 'Attribute' object has no attribute 'id'
```

- defaults are not recorded when the value is False, 0, '', ..

**Comment by aviaIguazio** [comment]
created a code contains 3 classes and a handler function 
running the code local succeeds
when trying to export function  (fn.export('function.yaml'))  getting
`AttributeError:` 'Attribute' object has no attribute 'id' ` 
removing one of the classes from the code results with success in export

you can see full notebook in my fork of mlrun/functions
https://github.com/aviaIguazio/functions/blob/development/query_parquet/query_parquet.ipynb

the code that fails to export
`class PrestoClient(object):
    def __init__(self, logger, presto_uri, user_name, access_key):
        self.logger = logger
        self.presto_uri = presto_uri
        self.user_name = user_name
        self.access_key = access_key
        self.cursor = None

    def connect(self):
        req_kw = {'auth': (self.user_name, self.access_key), 'verify': False}
        self.cursor = presto.connect(self.presto_uri, port=443, username=self.user_name,
                                     protocol='https', requests_kwargs=req_kw).cursor()
        self.logger.info("connected to presto")

    def disconnect(self):
        self.cursor.close()

    def execute_command(self, command):
        self.logger.info("executing command {}".format(command))
        self.cursor.execute(command)
        response = self.cursor.fetchone()
        self.logger.info("cursor response {}".format(response))


class ParquetFile(object):
    def __init__(self, logger, file_path):
        self.logger = logger
        self.path = file_path
        self.schema = None
        self.set_schema(file_path)

    def set_schema(self, file_path):
        schema = read_schema(file_path)
        self.schema = schema

    def schema_to_tuple(self):
        schema_names = self.schema.names
        schema_types = self.schema.types
        schema_tuple = tuple(zip(schema_names, schema_types))
        return schema_tuple

class HiveTable(object):     
    def __init__(self, logger,user_name, name='hive_table', db_schema='default', location=os.getcwd()):
        self.logger = logger
        self.name = name
        self.db_schema = db_schema
        self.location = self.set_location(location, user_name)
        self.schema = None

    def set_location(self, location, user_name):
        dir_path = location + "/" + self.name + "/"        
        if not os.path.isdir(dir_path):
            os.mkdir(dir_path)
        dir_path = dir_path.replace('/User/', 'v3io://users/'+user_name+'/')    
        return dir_path

    def generate_create_table_script_from_parquet(self, pqt: ParquetFile):
        self.set_schema_from_parquet(pqt.schema_to_tuple())
        command = "CREATE TABLE " + "hive." \
                  + self.db_schema \
                  + "." + self.name \
                  + self.schema \
                  + " WITH (format = 'PARQUET' , " \
                  + " external_location = '" + self.location \
                  + "')"
        
        return command    
    
    def set_schema_from_parquet(self, parquet_schema):
        fields = "("
        for field, value in parquet_schema:
            fields += field + ' ' + str(value) + ','
        fields = fields[:-1]
        fields += ")"
        fields = fields.replace('string', 'VARCHAR')
        fields = fields.replace('bool', 'BOOLEAN')
        self.schema = fields    


def query_parquet(context, file_path, v3io_access_key, user_name, presto_uri, hive_table_name='hive_table_name'):
    """query_parquet function
    
    query parquet file via oresto over hive metastore    
    
    :param file_path:  parquet file path
    
    :param hive_table_name: the name of the hive table that will be created in hive metastore
    """
    pqt = ParquetFile(context.logger, file_path)
    
    hive = HiveTable(context.logger,user_name, hive_table_name)
    
    create_table = hive.generate_create_table_script_from_parquet(pqt)
    
    cli = PrestoClient(context.logger, presto_uri, user_name,
                       v3io_access_key)
    cli.connect()

    cli.execute_command(create_table)
    
    cli.disconnect()`

**Comment by tebeka** [comment]
@yaronha I've written the following test which passes. Can you paste a complete example that fails?

```python
def test_annotate_mod():
    code = '''
    import mlrun

    def my_func(context, data: mlrun.DataItem):
        ...
    '''

    funcdoc.find_handlers(dedent(code))
```

**Comment by tebeka** [comment]
@yaronha I fail to see the zero value default problem - the test below passes. Any more information you can give me?

```python
def test_zero_default():
    code = dedent('''
    def sum_cart(cart, discount=0):
        total = sum(item.price*item.amount for item in cart)
        if discount:
            total *= (1-discount)
        return total
    ''')
    func, = funcdoc.find_handlers(code, handlers=['sum_cart'])
    assert func['params'][1]['default'] == '0'
```

**Comment by tebeka** [comment]
@yaronha The problem with zero default values is in `mlrun/run.py:925`

The `clean` function causes default zero value to be ignored. Since you wrote it :) how would you like to proceed?

**Comment by Hedingber** [comment]
@yaronha can I close this one ?
