### ISSUE TITLE
Nuclio function failed to deploy(MLRun CE 0.6.0-rc1 or mlrun 1.3.0)

### ISSUE THREAD

**Issue by harishgawade1999** [mlrun/mlrun#3428]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of MLRun CE.

### Reproducible Example

```python
2023-04-21 11:22:38,347 [warning] it is recommended to use k8s secret (specify secret_name), specifying the aws_access_key/aws_secret_key directly is unsafe
> 2023-04-21 11:22:38,351 [info] Starting remote function deploy
2023-04-21 11:22:38  (info) Deploying function
2023-04-21 11:22:38  (info) Building
2023-04-21 11:22:38  (info) Staging files and preparing base images
2023-04-21 11:22:38  (info) Building processor image
Failed to deploy. Details:


> 2023-04-21 11:29:10,574 [error] Nuclio function failed to deploy: {'function_state': 'error'}
---------------------------------------------------------------------------
RunError                                  Traceback (most recent call last)
Cell In [20], line 1
----> 1 project.deploy_function(serving_fn)

File /opt/conda/lib/python3.9/site-packages/mlrun/projects/project.py:2284, in MlrunProject.deploy_function(self, function, dashboard, models, env, tag, verbose, builder_env, mock)
   2262 def deploy_function(
   2263     self,
   2264     function: typing.Union[str, mlrun.runtimes.BaseRuntime],
   (...)
   2271     mock: bool = None,
   2272 ) -> typing.Union[DeployStatus, kfp.dsl.ContainerOp]:
   2273     """deploy real-time (nuclio based) functions
   2274 
   2275     :param function:    name of the function (in the project) or function object
   (...)
   2282     :param mock:        deploy mock server vs a real Nuclio function (for local simulations)
   2283     """
-> 2284     return deploy_function(
   2285         function,
   2286         dashboard=dashboard,
   2287         models=models,
   2288         env=env,
   2289         tag=tag,
   2290         verbose=verbose,
   2291         builder_env=builder_env,
   2292         project_object=self,
   2293         mock=mock,
   2294     )

File /opt/conda/lib/python3.9/site-packages/mlrun/projects/operations.py:366, in deploy_function(function, dashboard, models, env, tag, verbose, builder_env, project_object, mock)
    359     function.save()
    360     return DeployStatus(
    361         state="ready",
    362         outputs={"endpoint": "Mock", "name": function.metadata.name},
    363         function=function,
    364     )
--> 366 address = function.deploy(
    367     dashboard=dashboard, tag=tag, verbose=verbose, builder_env=builder_env
    368 )
    369 # return object with the same outputs as the KFP op (allow using the same pipeline)
    370 return DeployStatus(
    371     state=function.status.state,
    372     outputs={"endpoint": address, "name": function.status.nuclio_name},
    373     function=function,
    374 )

File /opt/conda/lib/python3.9/site-packages/mlrun/runtimes/serving.py:629, in ServingRuntime.deploy(self, dashboard, project, tag, verbose, auth_info, builder_env)
    626     self._deploy_function_refs()
    627     logger.info(f"deploy root function {self.metadata.name} ...")
--> 629 return super().deploy(
    630     dashboard, project, tag, verbose, auth_info, builder_env=builder_env
    631 )

File /opt/conda/lib/python3.9/site-packages/mlrun/runtimes/function.py:576, in RemoteRuntime.deploy(self, dashboard, project, tag, verbose, auth_info, builder_env)
    572 self._update_credentials_from_remote_build(data["data"])
    574 # when a function is deployed, we wait for it to be ready by default
    575 # this also means that the function object will be updated with the function status
--> 576 self._wait_for_function_deployment(db, verbose=verbose)
    578 # NOTE: on older mlrun versions & nuclio versions, function are exposed via NodePort
    579 #       now, functions can be not exposed (using service type ClusterIP) and hence
    580 #       for BC we first try to populate the external invocation url, and then
    581 #       if not exists, take the internal invocation url
    582 if self.status.external_invocation_urls:

File /opt/conda/lib/python3.9/site-packages/mlrun/runtimes/function.py:655, in RemoteRuntime._wait_for_function_deployment(self, db, verbose)
    653 if state != "ready":
    654     logger.error("Nuclio function failed to deploy", function_state=state)
--> 655     raise RunError(f"function {self.metadata.name} deployment failed")

RunError: function serving deployment failed
```

## Issue Description

I'm using Docker to work with Kubernetes.  I have installed and updated to new mlrun version (i.e **mlrun ce 0.6.0-rc1 or 1.3.0**). when I ran "Quick start" notebook, I encountered above error. I'm working with "Quick-start Tutorial "https://docs.mlrun.org/en/latest/tutorial/01-mlrun-basics.html". 

### **I have installed mlrun ce-rc1 by using following commands.**

kubectl create namespace mlrun

helm repo add mlrun-ce https://mlrun.github.io/ce

helm repo ls

helm repo update

kubectl --namespace mlrun create secret docker-registry registry-credentials --docker-server "https://registry.hub.docker.com" --docker-username "xxx" --docker-password "xxx" --docker-email "xxx"

helm install -n mlrun --values values.yaml --devel --wait --timeout 2000s --set global.registry.url="registry.hub.docker.com/xxx" --set global.registry.secretName="registry-credentials" --set global.externalHostAddress="192.168.0.57" mlrun-ce mlrun-ce/mlrun-ce

The values file which i have used here to install mlrun version is this- "https://github.com/mlrun/ce/blob/mlrun-ce-0.6.0-rc1/charts/mlrun-ce/values.yaml"

### It should get deployed without any error. for now, its showing following error on Nuclio .

[16:41:09.104] (I) Deploying function [requestID: "nuclio-dashboard-6677788464-nbkwj/LNF6lalZGc-000616"]
[16:41:09.107] (I) Building [builderKind: "kaniko", versionInfo: "Label: 1.11.8, Git commit: 534ce403e0b23439ddc0b6de76e056a01a435c0c, OS: linux, Arch: amd64, Go version: go1.17.10"]
[16:41:09.121] (I) Staging files and preparing base images
[16:41:09.123] (I) Building processor image [registryURL: "registry.hub.docker.com/harishgawade199", taggedImageName: "processor-quick-tutorial-jovyan-serving:latest"]
[16:46:54.685] (I) Build complete [image: "processor-quick-tutorial-jovyan-serving:latest"]
[16:46:55.035] (W) Function creation failed, updating function status [errorStack: "
Error - NuclioFunction in error state:

Error - the server could not find the requested resource
...//nuclio/pkg/platform/kube/functionres/lazy.go:757

Call stack:
Failed to create resource
...//nuclio/pkg/platform/kube/functionres/lazy.go:757
Failed to create/update HPA
...//nuclio/pkg/platform/kube/functionres/lazy.go:230
Failed to create/update function
.../platform/kube/controller/nucliofunction.go:213

...//nuclio/pkg/platform/kube/client/deployer.go:615
Call stack:
NuclioFunction in error state:

Error - the server could not find the requested resource
...//nuclio/pkg/platform/kube/functionres/lazy.go:757

Call stack:
Failed to create resource
...//nuclio/pkg/platform/kube/functionres/lazy.go:757
Failed to create/update HPA
...//nuclio/pkg/platform/kube/functionres/lazy.go:230
Failed to create/update function
.../platform/kube/controller/nucliofunction.go:213

...//nuclio/pkg/platform/kube/client/deployer.go:615
Failed to wait for function readiness.

Pod logs:

nuclio-quick-tutorial-jovyan-serving-995c8bf6f-79sxn
Failed to read logs: container "nuclio" in pod "nuclio-quick-tutorial-jovyan-serving-995c8bf6f-79sxn" is waiting to start: ContainerCreating

Warning events:

...//nuclio/pkg/platform/kube/client/deployer.go:155
", requestID: "nuclio-dashboard-6677788464-nbkwj/LNF6lalZGc-000616"]

## Installation OS

Windows

## Installation Method

Kubernetes

## Python Version

3.9.0

## MLRun Version

MLRun CE 0.6.0-rc1

## Additional Information

I'm using Docker(4.18.0), Kubectl(v1.27.0) and helm(v3.11.3) to work with mlrun CE.

**Comment by TomerShor** [comment]
@harishgawade1999 
You are using kubernetes v1.27 which is not tested at all in Nuclio or MLRun.

Function deployment fails due to failure to create its HPA. 
This could possibly be due to changes to the HPA definitions in later kubernetes versions, which is not dynamically configured in Nuclio.

Note that the latest tested version which is definitely supported is 1.24

**Comment by harishgawade1999** [comment]
Ok Thank you. So which tool I should use to work with Kubernetes v1.24....as docker does not have or support v1.24...

**Comment by harishgawade1999** [comment]
> @harishgawade1999 You are using kubernetes v1.27 which is not tested at all in Nuclio or MLRun.
> 
> Function deployment fails due to failure to create its HPA. This could possibly be due to changes to the HPA definitions in later kubernetes versions, which is not dynamically configured in Nuclio.
> 
> Note that the latest tested version which is definitely supported is 1.24

@TomerShor I have tried to work with v1.24 but still getting same error... can u please guide me about it...

**Comment by P8H** [comment]
Any news about this issue? I have the same problem with my fresh deployed MLrun instance on Kubernetes, see error log below.

MLrun CE: 1.2.1
K8s server: 1.26
```
 [14:08:24.254]  (I)  Deploying function   [requestID: "nuclio-dashboard-6d48f6d4f8-52lmd/LHBetOb8Tw-019731"] 
 [14:08:24.260]  (I)  Building   [builderKind: "kaniko", versionInfo: "Label: 1.11.8, Git commit: 534ce403e0b23439ddc0b6de76e056a01a435c0c, OS: linux, Arch: amd64, Go version: go1.17.10"] 
 [14:08:24.277]  (I)  Staging files and preparing base images    
 [14:08:24.278]  (I)  Building processor image   [registryURL: "europe-west3-docker.pkg.dev/**/**-docker-reg", taggedImageName: "processor-quick-tutorial-jovyan-serving:latest"] 
 [14:12:49.475]  (I)  Build complete   [image: "processor-quick-tutorial-jovyan-serving:latest"] 
 [14:12:49.803]  (W)  Function creation failed, updating function status   [errorStack: "
Error - NuclioFunction in error state:

Error - the server could not find the requested resource
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:757

Call stack:
Failed to create resource
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:757
Failed to create/update HPA
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:230
Failed to create/update function
    .../platform/kube/controller/nucliofunction.go:213

    ...//nuclio/pkg/platform/kube/client/deployer.go:615

Call stack:
NuclioFunction in error state:

Error - the server could not find the requested resource
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:757

Call stack:
Failed to create resource
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:757
Failed to create/update HPA
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:230
Failed to create/update function
    .../platform/kube/controller/nucliofunction.go:213

    ...//nuclio/pkg/platform/kube/client/deployer.go:615
Failed to wait for function readiness.

Pod logs:

* nuclio-quick-tutorial-jovyan-serving-78cf786b85-2vt2x
Failed to read logs: container "nuclio" in pod "nuclio-quick-tutorial-jovyan-serving-78cf786b85-2vt2-f82f5f7cf8" is waiting to start: ContainerCreating

* Warning events:


    ...//nuclio/pkg/platform/kube/client/deployer.go:155
", requestID: "nuclio-dashboard-6d48f6d4f8-52lmd/LHBetOb8Tw-019731"] 
```

**Comment by TomerShor** [comment]
@P8H As I wrote above, MLRun CE comes with an older version of Nuclio, which uses the [deprecated HPA api](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125).

The next CE version will contain the latest Nuclio which uses the latest API.

It has been tested with kubernetes v1.24 and should work.
@harishgawade1999 can you please verify the versions of both mlrun-ce and k8s that you are using?
If the issue still persists can you please attach the logs?

**Comment by P8H** [comment]
I can confirm that changing the K8s version to 1.23 has solved this issue.
Thanks for help!

**Comment by harishgawade1999** [comment]
I was able to resolve this error by updating K8s to version 1.24, thus I'm closing this issue.
