### ISSUE TITLE
[Bug]: RedisNoSqlTarget - OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#4845]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of MLRun CE.

### Reproducible Example

```python
import mlrun
import mlrun.feature_store as fstore
from mlrun.datastore.targets import RedisNoSqlTarget, ParquetTarget
from mlrun.features import Feature
import pandas as pd

def test():
    project_name = "my-project"
    feature_name = "fs-01"

    mlrun.set_env_from_file("mlrun-nonprod.env")
    project = mlrun.get_or_create_project(project_name, context='./', user_project=False)
    feature_set = fstore.FeatureSet(feature_name, entities=[fstore.Entity("party-id", value_type=mlrun.data_types.data_types.ValueType.STRING)],
                                    engine="storey")
    feature_set.add_feature(Feature(value_type=mlrun.data_types.data_types.ValueType.DATETIME),"party-establishment")
    feature_set.add_feature(Feature(value_type=mlrun.data_types.data_types.ValueType.STRING),"party-type")
    feature_set.add_feature(Feature(value_type=mlrun.data_types.data_types.ValueType.DATETIME),"party-typedate")

    # ERR - RedisNoSqlTarget generate issue see
    # OSError: [Errno 22] Invalid argument
    #   File "C:\Python\localRedisTest\venv\lib\site-packages\storey\redis_driver.py", line 161, in _convert_python_obj_to_lua_value
    #     return f'"{cls.DATETIME_FIELD_PREFIX}{value.timestamp()}"'
    feature_set.set_targets(targets=[RedisNoSqlTarget(name="a3", path="redis://localhost:6379")],with_defaults=False)

    # OK - Target Parquest works correctly
    #feature_set.set_targets(targets=[ParquetTarget(name="a1", path="./aa/")],with_defaults=False)
    feature_set.save()

    # ingest data with bundl/chunk
    for data_frm in pd.read_csv(f"c:/Python/localRedisTest/01-basic-party.csv",
                                sep=";", header="infer", decimal=",", compression=None, encoding="utf-8", chunksize=10000):
        fstore.ingest(feature_set, data_frm, return_df=False,
                      infer_options=mlrun.data_types.data_types.InferOptions.Null)
```

### Issue Description

See exception
...
  File "C:\Python\localRedisTest\venv\lib\site-packages\storey\redis_driver.py", line 243, in _build_feature_store_lua_update_script
    expression_value = self._convert_python_obj_to_lua_value(value)
  File "C:\Python\localRedisTest\venv\lib\site-packages\storey\redis_driver.py", line 161, in _convert_python_obj_to_lua_value
    return f'"{cls.DATETIME_FIELD_PREFIX}{value.timestamp()}"'
OSError: [Errno 22] Invalid argument

The sample works correctly in case that:

- I used ParquetTarget (RedisNoSqlTarget generate error)
- or if I used infer_options=InferOptions.default()

### Expected Behavior

Expected behavioral: Without exception also for mlrun.data_types.data_types.InferOptions.Null (It works correctly for ParquetTarget)

NOTE: I attached csv file for sample and I used redis in localhost:6379, I used python library redis==5.0.0
[01-basic-party.csv](https://github.com/mlrun/mlrun/files/13799026/01-basic-party.csv)

### Installation OS

Windows

### Installation Method

Docker

### Python Version

3.9.10

### MLRun Version

1.5.2

**Comment by assaf758** [comment]
issue does not seem reproducible with 1.6.0-rc18 @george0st can you confirm?

**Comment by george0st** [comment]
Hi @assaf758 , I played:

1] I tested MLRun to 1.6.0-rc18 on client side only (I used mlrun 1.5.2 in container) and the issue still exist
2] I updated MLRun in docker to 1.6.0-rc18 (see printscreen) also via update of compose.with-jupyter.yaml and all seems fine in docker desktop, but I was not able to connect to MLRun (also the access via http://localhost:8080/api/v1/projects was without success). Unfortunately, I am not able to finish this second test.

![mlrun 1 6 0-rc18](https://github.com/mlrun/mlrun/assets/95856749/b4fe8fd5-2120-4a12-b14d-52644c3ae301)

**Comment by alxtkr77** [comment]
@george0st , could you attach please 'pip freeze' output?

**Comment by george0st** [comment]
Hi @alxtkr77, pip freeze from client side with MLRun 1.5.2

[mlrun1-5-2.txt](https://github.com/mlrun/mlrun/files/13801592/mlrun1-5-2.txt)

**Comment by alxtkr77** [comment]
The issue arises due to a bug in Python on Windows, as documented in [Python's CPython issue #94757](https://github.com/python/cpython/issues/94757). This bug becomes apparent when a timestamp, which is either earlier than January 1, 1970, or later than January 19, 2038, is passed to the Redis driver. The Redis driver utilizes the `datetime.timestamp()` method to convert datetime objects to Unix epoch time, and this conversion process is where the fault occurs. It's important to note that this problem is specific to the Windows platform. However, MLRun officially supports Windows through Windows Subsystem for Linux (WSL) only, as outlined in the [MLRun documentation](https://docs.mlrun.org/en/latest/install/remote.html#mlrun-client-supported-os).

**Comment by george0st** [comment]
Hi @alxtkr77 , clear. Please, three points:
1] Is it possible to use this work-around (add timezone to datetime)? These samples work correctly in OS Window also.

```
>>> import datetime
>>> datetime.datetime(year=2021, month=11, day=13, tzinfo=datetime.timezone.utc).timestamp()
1636761600.0
>>> datetime.datetime(year=1021, month=11, day=13, tzinfo=datetime.timezone.utc).timestamp()
-29920233600.0
>>> datetime.datetime(year=3021, month=11, day=13, tzinfo=datetime.timezone.utc).timestamp()
33193670400.0
```
see original post about it https://github.com/python/cpython/issues/94757#issuecomment-1183633735

2] Why do you use this conversion only for infer_options=mlrun.data_types.data_types.InferOptions.Null? It works without calling of timestamp for InferOptions.Default())
BTW: I personally expect that in case of InferOptions.Null, it will be possible to avoid "discovery mode"

3] About WSL, you are right, I saw it from MLRun>=1.5.0 in documentation. Are there other blockers for use OS Windows (like datetime.timestamp)?

**Comment by alxtkr77** [comment]
Hello @george0st,

1. and 3. Unfortunately, there may be additional instances that require Windows support beyond this specific case. We haven't systematically identified all the gaps as we no longer conduct tests on Windows.

2. Regarding inference set to default: in this scenario, the attribute type in question is interpreted as a string, not as a datetime. Consequently, it undergoes a different processing pathway.

**Comment by assaf758** [comment]
@george0st we currently support python 3.9 only: https://docs.mlrun.org/en/latest/install/remote.html#prerequisites

**Comment by george0st** [comment]
Thx, I am closing this issue.
