### ISSUE TITLE
[Docs]: from mlrun.mlutils import eval_model_v2

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#5021]
### MLRun Kit version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://docs.mlrun.org/en/latest/)

### Location of the documentation

See sample 

- https://docs.mlrun.org/en/latest/store/models.html#model-artifacts
- https://docs.mlrun.org/en/latest/training/working-with-data-and-model-artifacts.html#plot-artifacts
- https://docs.mlrun.org/en/latest/training/working-with-data-and-model-artifacts.html#model-artifacts

### Documentation problem

Invalid reference "from mlrun.mlutils import eval_model_v2", valid reference is "from mlrun.utils import eval_model_v2"

### Suggested fix for documentation

Mention relevant package **mlrun.utils**

**Comment by jillnogold** [comment]
https://github.com/mlrun/mlrun/pull/5030
