### ISSUE TITLE
[Docs]: Invalid reference to quick-start page

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#5022]
### MLRun Kit version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://docs.mlrun.org/en/latest/)

### Location of the documentation

Page

- https://docs.mlrun.org/en/stable/store/models.html reference and problematic reference to the [quick-start page](https://docs.mlrun.org/en/stable/store/quick-start.html#mlrun-setup) 

### Documentation problem

Invalid reference [quick-start page](https://docs.mlrun.org/en/stable/store/quick-start.html#mlrun-setup) 

### Suggested fix for documentation

Repair link

**Comment by jillnogold** [comment]
https://github.com/mlrun/mlrun/pull/5030
