### ISSUE TITLE
[Bug]: Strange location for CSVTarget (location is out of project directory)

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#5056]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of MLRun CE.

### Reproducible Example

```python
import mlrun
import mlrun.feature_store as fstore
from mlrun.datastore.targets import CSVTarget, ParquetTarget
from mlrun.data_types.data_types import ValueType
import pandas as pd
import numpy
import sys
import os


def csvtarget_issue():

    mlrun.set_env_from_file("mlrun-nonprod.env")

    project_name="a1"
    project = mlrun.get_or_create_project(project_name, context='./output/a1/', user_project=False)
    project.description = "a1 description"
    project.save()

    feature_name="basic-party"
    feature_set = fstore.FeatureSet(feature_name, entities=[fstore.Entity("party-id", value_type=ValueType.INT64)],
                                    engine="storey")
    feature_set.add_feature(fstore.Feature(name="party-type"))
    feature_set.set_targets(targets=[ParquetTarget(name="target_0",
                                                   path=os.path.join("./output/","a1", "target_0")),
                                     CSVTarget(name="target_1",
                                              path=os.path.join("./output/","a1", "target_1",
                                                                "target_1" + ".csv"))],
                            with_defaults=False)
    feature_set.save()
    data={"party-id": [1,2,3],
          "party-type": ["a1", "b2", "c3"]}
    dataFrm=pd.DataFrame(data)
    fstore.ingest(feature_set,dataFrm,overwrite=True)

if __name__ == '__main__':
    csvtarget_issue()
```

### Issue Description

When I used two targets, first is ParquetTarget and second CSVTarget, than location of CVS output used the strange path see 'output\1707051857682_445\a1\target_1\target_1.csv' it is not the path under the project (location of ParquetTarget is under the project but CSVTarget is out of the project path 'output\a1').

To be honest, I do not know if it is the issue or my missing knowledge, many thanks for the help with that.

![image](https://github.com/mlrun/mlrun/assets/95856749/2f5425e8-2437-466b-adfa-705508ae2328)

### Expected Behavior

The CSVTarget will have location **output\a1\target_1\.**... similar such as ParquetTarget (it means with the same beginning output\a1\), see easy visualization:

```
-output
  |-a1
    |-target_0
    |-target_1
```

not the

```
-output
  |-1707051857682_445
    |-target_1
  |-a1
    |-target_0
```

### Installation OS

Windows

### Installation Method

Docker

### Python Version

3.9.10

### MLRun Version

1.5.2

**Comment by george0st** [comment]
NOTE: The output is the same in case of absolute path in CSVTarget see
```
                                      CSVTarget(name="target_1",
                                              path=os.path.join("c:/Python/test/output/","a1", "target_1",
                                                                "target_1" + ".csv")),
```

**Comment by george0st** [comment]
Hi @liranbg, I am not sure if it is issue or not (expected behavior), please let me know (everything is under project except content of CSVTarget).

**Comment by gtopper** [comment]
Hi @george0st, I don't have a Windows machine immediately available, but I think the issue is the use of `os.path.join`, which on Windows will join the path with backslash separators.

Does replacing
```python
os.path.join("./output/","a1", "target_1", "target_1" + ".csv")
```
with
```python
"/".join(["./output","a1", "target_1", "target_1" + ".csv"])
```
resolve the issue?

**Comment by george0st** [comment]
Hi @gtopper , I will check it, thx

**Comment by george0st** [comment]
Hi @gtopper, you are right, your solution solved the issue, thanks.

Only note, I tested:

1. Situation, it generated the **ISSUE**

    - path=os.path.join(".", "output", "a1", "target_4", "target_4" + ".csv")
    - output >> '.\\output\\a1\\target_4\\target_4.csv' (it is valid path for OS Win, but generate ISSUE)

2. Situation, it is **OK**

   - path="/".join([".", "output", "a1", "target_1", "target_1" + ".csv"])
   - output >> './output/a1/target_1/target_1.csv' (it is valid path for OS Win, Linux and works OK)
