### ISSUE TITLE
[Installation]: Failed to load port 8080 with docker setup

### ISSUE THREAD

**Issue by ttu-nguyen** [mlrun/mlrun#5154]
### Installation check

- [X] I have read the [installation guide](https://docs.mlrun.org/en/latest/install.html).

### Installation OS

Mac

### Installation Method

Docker

### Kubernetes Cluster Type

N/A - Docker

### MLRun CE Version

1.5.1

### Issue Description

Hello, 

I've followed the installation guide on my local Mac M2 with `docker-compose`.  
The build steps finished without any error. 
<img width="442" alt="Screenshot 2024-02-18 at 23 42 19" src="https://github.com/mlrun/mlrun/assets/95226838/850153d6-2826-4c41-b4bd-340d212b1883">

However, when I display containers, it showed that containers `mlrun-nuclio-1`, `mlrun-mlrun-ui-1`, `mlrun-jupyter-1` worked well with successful status. but the container `mlrun-init_nuclio-1` failed and exited right away. 
<img width="1471" alt="Screenshot 2024-02-18 at 23 42 44" src="https://github.com/mlrun/mlrun/assets/95226838/506bb825-b7f5-428c-be16-9fbacbe102a7">

That's why `localhost:8080` failed to load. 

### Installation Logs

<details>

No error logs displayed.
</details>

**Comment by alonmr** [comment]
Hi @ttu-nguyen, this issue is quite stale however, docker setup is not a thing anymore for mlrun. We now require a kubernetes cluster. Please see https://docs.mlrun.org/en/latest/install/kubernetes.html#install-on-kubernetes if still needed.
