### ISSUE TITLE
Error installing mlrun

### ISSUE THREAD

**Issue by keithpij** [mlrun/mlrun#5470]
I am trying to install the mlrun python library into a virtual environment on my Mac, and I am getting the following error when I run "pip install mlrun".

Collecting pyyaml~=5.1 (from mlrun)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]

It looks like the version of PyYAML required by MLRun is not working. Is there a workaround? I tried a few things but did not have any success.

The version of Python I am using is 3.9.13

**Comment by liranbg** [comment]
Hi @keithpij ,
Are you installing MLRun atop arm by any chance?

**Comment by keithpij** [comment]
Hi @liranbg, No, I am on a Mac. It has the Apple M2 Pro chip.

**Comment by liranbg** [comment]
Apple M2 chip is arm64 based system. Have you followed https://github.com/mlrun/mlrun/blob/development/CONTRIBUTING.md#developing-with-arm64-machines ?

**Comment by keithpij** [comment]
Hi @liranbg, I am getting the same error on my Windows machine with an Intel i7 chip. The error above occurs while I am installing mlrun. I am not running anything.

**Comment by keithpij** [comment]
Hi @liranbg, Do you have an update on this issue? It is blocking a few tasks I am working on. Basically, I am working on a presentation that I will be giving at several conferences this year. I want to compare several MLOps tools. It would be nice if I could include MLRun - a lot of the features on your site sound valuable to the ML pipeline. I could use the Jupyter notebook you package up with your deployment but I really want to show demos from a development tool.

**Comment by george0st** [comment]
FYI @xsqian

**Comment by keithpij** [comment]
@liranbg @george0st @xsqian Any thoughts on this issue?

**Comment by george0st** [comment]
Hi @keithpij, which pip version do you use?

NOTE: I used 24.0, you can check version via `pip --version`

**Comment by keithpij** [comment]
@george0st I am also using 24.0. Does it work for you?

**Comment by george0st** [comment]
@keithpij, It works fine with pip 24.0. Did you test to install MLRun without virtual environment? 

Which virtual env. do you use?

**Comment by keithpij** [comment]
@george0st I tried to install it in a Python virtual environment that has Python 3.9.13. (The same version that is in the Jupyter image from the Docker Compose install option.) I got the same error on both my Mac and my Windows machine.

I also get the same error when I try to install without a virtual environment.

**Comment by alonmr** [comment]
Hey @keithpij ,this seems to be a known issue with pyyaml. Please see https://github.com/yaml/pyyaml/issues/724
Since you are not running with conda, you can downgrade pyyaml to 5.3 and after you do so installing mlrun should not upgrade it. Or you can follow any other suggestion on the issue I linked. I don't see a reason to make any changes in mlrun since if you follow the https://github.com/mlrun/mlrun/blob/development/CONTRIBUTING.md#developing-with-arm64-machines guidelines everything works with pyyaml 5.4.1 as well.

**Comment by keithpij** [comment]
@george0st @xsqian @liranbg FYI - I am using PyEnv (https://github.com/pyenv/pyenv) to manage Python versions. I have never had a problem with PyEnv but maybe it is doing something to your stuff.
