### ISSUE TITLE
FEATURE: Update setup.py to support multiple extras_requires

### ISSUE THREAD

**Issue by ihs-nick** [mlrun/mlrun#551]
MLRun has a lot of functionality. From being able to do training jobs to serving. It supports multiple cloud providers and runtimes. However, not everyone needs all of those options when they install MLRun - especially in production. This means there is an opportunity to allow users to choose the support they would like from MLRun when installing it - [much like dask does](https://docs.dask.org/en/latest/install.html#optional-dependencies).

I think it makes sense to add optional installs for cloud providers - meaning you could specify `pip install mlrun['aws']` and get boto3 without azure/google. Similarly, if you only need the serving api and azure access, you could specify `pip install mlrun['azure', 'serving']`. This is not to say that `pip install mlrun` shouldn't include everything for simplicity, but there are a lot of dependencies for that kind of an install due to the awesome amount of functionality provided by mlrun. 

Beyond reducing function sizes when installing, I think this dependency update is a best practice to enable projects migrating to mlrun with previously declared dependencies. The more mlrun requires ==, >= <=, etc. the higher the chance that one of the dependencies in the incoming code will not work with mlrun. From an adoption standpoint, this would slow down older projects migrating.

I hope you will consider this in the upcoming release or very soon.

**Comment by Hedingber** [comment]
Hi @ihs-nick,

Thanks for reaching out!

This is definitely in our short term road map, I believe we'll have it for 0.6.0

**Comment by ihs-nick** [comment]
Thanks for the update @Hedingber. Any clarity on what options you are going to provide for installation?

**Comment by Hedingber** [comment]
@ihs-nick 
I don't know yet

**Comment by Hedingber** [comment]
Hi @ihs-nick,
Thanks again for putting the time on submitting the issue and writing the detailed description,
Implemented it in https://github.com/mlrun/mlrun/pull/620, details are in the PR description
