### ISSUE TITLE
[error] error submitting build task: 400 Client Error: Bad Request for url: http://localhost:8080/api/v1/build/function: details: {'reason': "Runtime error: 'K8sHelper' object has no attribute 'v1api'"}, caused by: 400 Client Error: Bad Request for url: http://localhost:8080/api/v1/build/function

### ISSUE THREAD

**Issue by kumar-ujjwal-800** [mlrun/mlrun#5580]
### Discussed in https://github.com/mlrun/mlrun/discussions/5579

<div type='discussions-op-text'>

<sup>Originally posted by **ujjwal-here-h** May 16, 2024</sup>
I am attempting to execute the tutorial notebook found at: [MLRun Model Monitoring and Drift Detection](https://docs.mlrun.org/en/stable/tutorials/05-model-monitoring.html).

However, while running this line - `project.deploy_function(serving_fn)` I encounter the following error:

```[error] error submitting build task: 400 Client Error: Bad Request for url: http://localhost:8080/api/v1/build/function: details: {'reason': "Runtime error: 'K8sHelper' object has no attribute 'v1api'"}, caused by: 400 Client Error: Bad Request for url: http://localhost:8080/api/v1/build/function```

I did some testing and figured out that this issue specifically arises when I use the following line of code:
#### `serving_fn.set_tracking()  `                #for enabling model monitoring

If I comment out this line, the deployment proceeds without issues using `project.deploy_function(serving_fn)`

However, if I execute serving_fn.set_tracking(), I receive the previously mentioned error. The error message suggests that the deployment is looking for a Kubernetes cluster, but I have not configured one and am using Docker instead.

Could there be a parameter that can be set to direct the deployment to a local (Docker) environment? I tried setting local = True here:

`serving_fn.add_model( "cancer-classifier", model_path=trainer_run.outputs["model"], class_name="mlrun.frameworks.sklearn.SklearnModelServer", local =True)`

but it didn't solve the issue.

MLRun is installed on Docker. I can access the following components:
MLRun UI (in http://localhost:8060/)
Nuclio Dashboard/controller (in http://localhost:8070/)
MLRun API (in http://localhost:8080/) --> returns {"detail":"Not Found"}

I run the tutorial code in my IDE and I can see the project in the MLRun UI. Everything seems to work fine but when it comes to serving a function using the deploy_function it fails with the above error. It would be very nice if someone could tell me what's wrong with the configuration or what is supposed to be the API call that would work.</div>

**Comment by alonmr** [comment]
Hi @ujjwal-here-h , MLRun now requires a kubernetes cluster. Please see https://docs.mlrun.org/en/latest/install/kubernetes.html#install-on-kubernetes if still an issue.
