### ISSUE TITLE
Installation guide nuclio and mlrun reversed 

### ISSUE THREAD

**Issue by ihs-nick** [mlrun/mlrun#827]
In the installation guide, the links to nuclio and mlrun are actually the opposite. It should be mlrun that goes to 30060 and nuclio to 30050.

![image](https://user-images.githubusercontent.com/70656471/112079200-59c4b500-8b45-11eb-9cb8-9194e8ee3bcf.png)

**Comment by omesser** [comment]
Thanks @ihs-nick  - yes we need to update it according to https://github.com/v3io/helm-charts/blob/development/stable/mlrun-kit/README.md

@gilad-shaham
