### ISSUE TITLE
BUG: child function object is not callable

### ISSUE THREAD

**Issue by ihs-nick** [mlrun/mlrun#881]
https://github.com/mlrun/mlrun/blob/e3569244588d835a0028f07605f5789b51bc27df/mlrun/runtimes/serving.py#L340

```
child_function.function_object().add_v3io_stream_trigger(
TypeError: 'ServingRuntime' object is not callable
```

The parentheses should be removed to work properly.

**Comment by Hedingber** [comment]
@ihs-nick Thanks for reporting the issue and fixing it
https://github.com/mlrun/mlrun/pull/882 was merged, closing

**Comment by ihs-nick** [comment]
Thanks @Hedingber! Any chance this fix will be backported into older versions of mlrun that contain the bug, like 0.6.2?

**Comment by Hedingber** [comment]
@ihs-nick we're expecting to release 0.6.3 by the end of this week, so I don't think there's a reason to backport
