### ISSUE TITLE
Request Github Discussions be added to the project

### ISSUE THREAD

**Issue by nicklausbrown** [mlrun/mlrun#980]
Hello! I was hoping that this project could enable the [ Github Discussions ](https://docs.github.com/en/discussions) tab. It would be a great to have this for the Q&A functionality as well as a place to talk about the API and functionality. Having a discussions area would prevent issues being raised that are not actually issues. @Hedingber @yaronha, what do you think?

**Comment by Hedingber** [comment]
@nicklausbrown Sounds good, enabled it, thanks for the suggestion!
